# Generated by Django 3.2.16 on 2023-09-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactor',
            name='input_tubeid',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True, verbose_name='Tube ID value'),
        ),
    ]
