# Generated by Django 4.1.1 on 2022-09-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_categoryfield_selectfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfield',
            name='selectfield',
            field=models.IntegerField(choices=[('value1', 'value1'), ('value2', 'value2'), ('value3', 'value3')], default=1),
        ),
    ]
