# Generated by Django 4.1.1 on 2022-09-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_delete_categoryfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectfield', models.IntegerField(choices=[('value1', 'value1'), ('value2', 'value2'), ('value3', 'value3')], default=1)),
                ('verified', models.BooleanField(default=True, verbose_name='Required?')),
            ],
        ),
    ]
