# Generated by Django 4.1.1 on 2022-09-21 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_categoryfield'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryField',
        ),
    ]
