# Generated by Django 4.1.1 on 2022-09-21 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_tubeidmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TubeidModel',
        ),
    ]
