# Generated by Django 4.1.1 on 2022-09-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_tubeidmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactor',
            name='tube_id',
            field=models.CharField(max_length=15),
        ),
    ]
