# Generated by Django 4.1.1 on 2022-09-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_alter_reactor_tube_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactor',
            name='tube_id',
            field=models.CharField(blank=True, choices=[('INCH', 'INCH'), ('MM', 'MM')], default='INCH', max_length=128, verbose_name='Tube ID'),
        ),
    ]
