# Generated by Django 4.1.1 on 2022-09-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_alter_reactor_tube_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DropdownModel',
        ),
        migrations.AddField(
            model_name='reactor',
            name='inch',
            field=models.CharField(blank=True, max_length=128, verbose_name='INCH'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='mm',
            field=models.CharField(blank=True, max_length=128, verbose_name='MM'),
        ),
        migrations.AddField(
            model_name='tubeidmodel',
            name='value2',
            field=models.CharField(default='', max_length=15),
        ),
    ]
