# Generated by Django 4.1.1 on 2022-09-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_delete_dropdownmodel_reactor_inch_reactor_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactor',
            name='inch1',
            field=models.CharField(blank=True, max_length=128, verbose_name='INCH'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='inch2',
            field=models.CharField(blank=True, max_length=128, verbose_name='INCH'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='mm1',
            field=models.CharField(blank=True, max_length=128, verbose_name='MM'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='mm2',
            field=models.CharField(blank=True, max_length=128, verbose_name='MM'),
        ),
    ]
