# Generated by Django 4.1.1 on 2022-09-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_reactor_inch1_reactor_inch2_reactor_mm1_reactor_mm2'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactor',
            name='inch3',
            field=models.CharField(blank=True, max_length=128, verbose_name='INCH'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='inch4',
            field=models.CharField(blank=True, max_length=128, verbose_name='INCH'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='inch5',
            field=models.CharField(blank=True, max_length=128, verbose_name='INCH'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='inch6',
            field=models.CharField(blank=True, max_length=128, verbose_name='INCH'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='inch7',
            field=models.CharField(blank=True, max_length=128, verbose_name='INCH'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='inch8',
            field=models.CharField(blank=True, max_length=128, verbose_name='INCH'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='mm3',
            field=models.CharField(blank=True, max_length=128, verbose_name='MM'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='mm4',
            field=models.CharField(blank=True, max_length=128, verbose_name='MM'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='mm5',
            field=models.CharField(blank=True, max_length=128, verbose_name='MM'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='mm6',
            field=models.CharField(blank=True, max_length=128, verbose_name='MM'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='mm7',
            field=models.CharField(blank=True, max_length=128, verbose_name='MM'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='mm8',
            field=models.CharField(blank=True, max_length=128, verbose_name='MM'),
        ),
    ]
