# Generated by Django 4.1.1 on 2022-09-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_alter_client_official_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='no_of_unit',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='reactor_per_each_unit',
        ),
    ]
