# Generated by Django 4.1.1 on 2022-09-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_remove_plant_no_of_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='no_of_unit',
            field=models.ManyToManyField(to='client.unit'),
        ),
    ]
