# Generated by Django 4.1.1 on 2022-09-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0023_unit_reactor_per_each_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='key_contact',
        ),
    ]
