# Generated by Django 4.1.1 on 2022-09-22 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0024_remove_client_key_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='no_of_unit',
            new_name='name_of_unit',
        ),
    ]
