# Generated by Django 4.1.1 on 2022-09-22 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0025_rename_no_of_unit_plant_name_of_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='no_of_unit',
            new_name='name_of_unit',
        ),
    ]
