# Generated by Django 4.1.1 on 2022-09-22 08:02

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0026_rename_no_of_unit_client_name_of_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name_of_unit',
            new_name='no_of_unit',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='name_of_unit',
            new_name='no_of_unit',
        ),
        migrations.AddField(
            model_name='client',
            name='key_contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
