# Generated by Django 4.1.1 on 2022-09-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0027_rename_name_of_unit_client_no_of_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='key_contact',
        ),
    ]
