# Generated by Django 4.1.1 on 2022-09-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0029_remove_client_no_of_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='no_of_unit',
            field=models.ManyToManyField(to='client.unit'),
        ),
        migrations.AddField(
            model_name='client',
            name='reactor_per_each_unit',
            field=models.ManyToManyField(to='client.reactor'),
        ),
    ]
