# Generated by Django 4.1.1 on 2022-09-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0030_client_no_of_unit_client_reactor_per_each_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='no_of_unit',
        ),
        migrations.RemoveField(
            model_name='client',
            name='reactor_per_each_unit',
        ),
    ]
