# Generated by Django 4.1.1 on 2022-09-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0031_remove_client_no_of_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactor',
            name='ferrule_id',
            field=models.CharField(blank=True, choices=[('INCH', 'INCH'), ('MM', 'MM')], default='INCH', max_length=128, verbose_name='Ferrule ID'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='ferrule_length',
            field=models.CharField(blank=True, choices=[('INCH', 'INCH'), ('MM', 'MM')], default='INCH', max_length=128, verbose_name='Ferrule Length'),
        ),
    ]
