# Generated by Django 4.1.1 on 2022-09-22 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0032_alter_reactor_ferrule_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='no_of_unit',
            new_name='name_of_unit',
        ),
    ]
