# Generated by Django 4.1.1 on 2022-09-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0034_remove_client_plant_client_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='plant',
        ),
        migrations.AddField(
            model_name='client',
            name='plant',
            field=models.ManyToManyField(to='client.plant'),
        ),
    ]
