# Generated by Django 4.1.1 on 2022-09-22 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0035_remove_client_plant_client_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Client', to='client.client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='plant',
            field=models.ManyToManyField(related_name='Plant', to='client.plant'),
        ),
    ]
