# Generated by Django 4.1.1 on 2022-09-22 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0036_plant_client_alter_client_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Client Address+', to='client.client'),
        ),
        migrations.AddField(
            model_name='contact',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Client Contact+', to='client.client'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Client Reactor+', to='client.client'),
        ),
        migrations.AddField(
            model_name='unit',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Client Unit+', to='client.client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_person',
            field=models.ManyToManyField(related_name='Client Contact+', to='client.contact'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Client Plant+', to='client.client'),
        ),
    ]
