# Generated by Django 4.1.1 on 2022-09-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0038_alter_reactor_is_there_ferrule_insert_in_tube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactor',
            name='is_there_ferrule_insert_in_tube',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=128, verbose_name='Is there ferrule insert in tube?'),
        ),
    ]
