# Generated by Django 4.1.1 on 2022-09-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0039_alter_reactor_is_there_ferrule_insert_in_tube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactor',
            name='top_dome_removable',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=128, verbose_name='Top Dom Removable'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='top_inlet_accessible',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=128, verbose_name='Top Inlet Accessible'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='top_inlet_impingment_plate',
            field=models.BooleanField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=128, verbose_name='Top Inlet Impingment Plate'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='tube_protude_out_of_bottom_tube_sheet',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=128, verbose_name='Tube Protude Out Of Bottom Tube Sheet'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='tube_protude_out_of_top_tube_sheet',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=128, verbose_name='Tube Protude Out Of Top Tube Sheet'),
        ),
    ]
