# Generated by Django 4.1.1 on 2022-09-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0040_alter_reactor_top_dome_removable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactor',
            name='top_inlet_impingment_plate',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=128, verbose_name='Top Inlet Impingment Plate'),
        ),
    ]
