# Generated by Django 4.1.1 on 2022-09-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0041_alter_reactor_top_inlet_impingment_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='client',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='client',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='client',
        ),
        migrations.RemoveField(
            model_name='reactor',
            name='client',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='client',
        ),
    ]
