# Generated by Django 4.1.1 on 2022-09-28 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0043_remove_client_contact_person_client_contact_person'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='client',
        #     name='contact_person',
        #     field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Client Contact+', to='client.contact'),
        # ),
    ]
