# Generated by Django 4.1.1 on 2022-09-28 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0045_alter_client_contact_person'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='client',
        #     name='contact_person',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Client Contact+', to='client.contact'),
        # ),
    ]
