# Generated by Django 4.1.1 on 2022-09-28 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0046_alter_client_contact_person'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='client',
        #     name='contact_person',
        # ),
    ]
