# Generated by Django 4.1.1 on 2022-09-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0047_remove_client_contact_person'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='client',
        #     name='contact_person',
        #     field=models.ManyToManyField(related_name='Client Contact+', to='client.contact'),
        # ),
    ]
