# Generated by Django 4.1.1 on 2022-10-03 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0050_client_contact_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='client',
            name='plant',
        ),
    ]
