# Generated by Django 4.1.1 on 2022-10-03 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0051_remove_client_contact_person_remove_client_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Client Plant+', to='client.client'),
        ),
    ]
