# Generated by Django 4.1.1 on 2022-10-03 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0052_plant_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='name_of_unit',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='reactor_per_each_unit',
        ),
        migrations.AddField(
            model_name='unit',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Plant Unit+', to='client.plant'),
        ),
    ]
