# Generated by Django 4.1.1 on 2022-10-03 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0054_reactor_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactor',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Unit Reactor+', to='client.unit'),
        ),
    ]
