# Generated by Django 4.1.1 on 2022-10-03 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0055_alter_reactor_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Client Address+', to='client.client'),
        ),
        migrations.AddField(
            model_name='contact',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Client Contact+', to='client.client'),
        ),
    ]
