# Generated by Django 4.1.1 on 2022-10-04 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0058_alter_client_contact_person_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TubeidModel',
        ),
    ]
