# Generated by Django 4.1.1 on 2022-10-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0063_remove_plant_client_client_plant_plant_name_of_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('toppings', models.ManyToManyField(to='client.topping')),
            ],
        ),
    ]
