# Generated by Django 4.1.1 on 2022-10-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0064_topping_pizza'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='pizza',
        #     name='toppings',
        #     field=models.ManyToManyField(related_name='pizzas', to='client.topping'),
        # ),
    ]
