# Generated by Django 4.1.1 on 2022-10-04 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0068_alter_pizza_toppings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppingamount',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='toppingamount',
            name='topping',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
        migrations.DeleteModel(
            name='ToppingAmount',
        ),
    ]
