# Generated by Django 4.1.1 on 2022-10-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0073_client_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='client',
        ),
        migrations.RemoveField(
            model_name='reactor',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='plant',
        ),
        migrations.AddField(
            model_name='plant',
            name='name_of_unit',
            field=models.ManyToManyField(related_name='plant Unit+', to='client.unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='reactor_per_each_unit',
            field=models.ManyToManyField(to='client.reactor'),
        ),
    ]
