# Generated by Django 4.1.1 on 2022-10-04 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0074_remove_plant_client_remove_reactor_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Client Plant+', to='client.client'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Unit Reactor+', to='client.unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Plant Unit+', to='client.plant'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='reactor_per_each_unit',
            field=models.ManyToManyField(related_name='Unit Reactor+', to='client.reactor'),
        ),
    ]
