# Generated by Django 4.1.1 on 2022-10-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0075_plant_client_reactor_unit_unit_plant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='client',
        ),
        migrations.RemoveField(
            model_name='reactor',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='plant',
        ),
    ]
