# Generated by Django 4.1.1 on 2022-10-10 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0079_remove_plant_name_of_unit_plant_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='reactor_per_each_unit',
        ),
        migrations.AddField(
            model_name='unit',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Client Plant+', to='client.client'),
        ),
        migrations.AddField(
            model_name='unit',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Plant Unit+', to='client.plant'),
        ),
    ]
