# Generated by Django 4.1.1 on 2022-10-10 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0080_remove_unit_reactor_per_each_unit_unit_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactor',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Reactor Client+', to='client.client'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Unit Reactor+', to='client.unit'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Plant Client+', to='client.client'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Unit Client+', to='client.client'),
        ),
    ]
