# Generated by Django 4.1.1 on 2022-10-10 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0081_reactor_client_reactor_unit_alter_plant_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientplant+', to='client.client'),
        ),
    ]
