# Generated by Django 4.1.1 on 2022-10-10 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0082_alter_plant_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactor',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Reactor Plant+', to='client.plant'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Reactor Unit+', to='client.unit'),
        ),
    ]
