# Generated by Django 4.1.1 on 2022-10-11 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0083_reactor_plant_alter_reactor_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactor',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactorclient+', to='client.client'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactorplant+', to='client.plant'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactorunit+', to='client.unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientunit+', to='client.client'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantunit+', to='client.plant'),
        ),
    ]
