# Generated by Django 4.1.1 on 2022-10-14 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0084_alter_reactor_client_alter_reactor_plant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='client',
        ),
    ]
