# Generated by Django 4.1.1 on 2022-11-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0087_remove_address_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='official_address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='plantentrance_address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='client',
            name='official_address',
            field=models.ManyToManyField(related_name='official_address', to='client.address'),
        ),
        migrations.AddField(
            model_name='client',
            name='plantentrance_address',
            field=models.ManyToManyField(related_name='plantentrance_address', to='client.address'),
        ),
        migrations.AddField(
            model_name='client',
            name='shipping_address',
            field=models.ManyToManyField(related_name='shipping_address', to='client.address'),
        ),
    ]
