# Generated by Django 4.1.1 on 2022-11-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0090_remove_client_official_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactor',
            name='tube_material_of_raws',
        ),
        migrations.AddField(
            model_name='reactor',
            name='tube_material_of_rows',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Raws'),
        ),
    ]
