# Generated by Django 4.1.1 on 2022-12-07 09:03

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0100_unit_country2_alter_unit_country_alter_unit_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='country',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='official_name', chained_model_field='official_name', on_delete=django.db.models.deletion.CASCADE, related_name='unitcountry', to='client.client'),
        ),
    ]
