# Generated by Django 4.1.1 on 2022-12-07 09:05

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0101_alter_unit_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='country',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='client', chained_model_field='client', on_delete=django.db.models.deletion.CASCADE, related_name='unitcountry', to='client.client'),
        ),
    ]
