# Generated by Django 4.1.1 on 2022-12-07 09:16

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0102_alter_unit_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='country',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='country2',
        ),
        migrations.AlterField(
            model_name='unit',
            name='plant',
            field=smart_selects.db_fields.GroupedForeignKey(default='', group_field='client', on_delete=django.db.models.deletion.CASCADE, related_name='unitplant', to='client.plant'),
        ),
    ]
