# Generated by Django 4.1.1 on 2022-12-07 12:21

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0103_remove_unit_country_remove_unit_country2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactor',
            name='plant',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='client', on_delete=django.db.models.deletion.CASCADE, related_name='reactorplant+', to='client.plant'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='unit',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='unit', on_delete=django.db.models.deletion.CASCADE, related_name='reactorunit+', to='client.unit'),
        ),
    ]
