# Generated by Django 4.1.1 on 2022-12-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0105_alter_reactor_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactor',
            name='inch',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='INCH'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='inch1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='INCH'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='inch2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='INCH'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='inch3',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='INCH'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='inch4',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='INCH'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='inch5',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='INCH'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='inch6',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='INCH'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='inch7',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='INCH'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='inch8',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='INCH'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='mm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='MM'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='mm1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='MM'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='mm2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='MM'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='mm3',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='MM'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='mm4',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='MM'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='mm5',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='MM'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='mm6',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='MM'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='mm7',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='MM'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='mm8',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='MM'),
        ),
    ]
