# Generated by Django 4.1.1 on 2022-12-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0106_alter_reactor_inch_alter_reactor_inch1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactor',
            name='inch7',
            field=models.PositiveIntegerField(blank=True, verbose_name='INCH'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='mm7',
            field=models.PositiveIntegerField(blank=True, verbose_name='MM'),
        ),
    ]
