# Generated by Django 4.1.1 on 2022-12-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0107_alter_reactor_inch7_alter_reactor_mm7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactor',
            name='inch7',
            field=models.PositiveIntegerField(null=True, verbose_name='INCH'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='mm7',
            field=models.PositiveIntegerField(null=True, verbose_name='MM'),
        ),
    ]
