# Generated by Django 4.1.1 on 2022-12-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0108_alter_reactor_inch7_alter_reactor_mm7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactor',
            name='bottom_tube_sheet_thickness',
            field=models.CharField(choices=[('INCH', 'INCH'), ('MM', 'MM')], max_length=128, verbose_name='Bottom Tube Sheet Thickness'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='ferrule_id',
            field=models.CharField(choices=[('INCH', 'INCH'), ('MM', 'MM')], max_length=128, verbose_name='Ferrule ID'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='ferrule_length',
            field=models.CharField(choices=[('INCH', 'INCH'), ('MM', 'MM')], max_length=128, verbose_name='Ferrule Length'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='inch7',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='INCH'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='is_there_ferrule_insert_in_tube',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=128, verbose_name='Is there ferrule insert in tube?'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='mm7',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='MM'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='top_dome_removable',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=128, verbose_name='Top Dom Removable'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='top_inlet_accessible',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=128, verbose_name='Top Inlet Accessible'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='top_inlet_impingment_plate',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=128, verbose_name='Top Inlet Impingment Plate'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='top_tube_sheet_thickness',
            field=models.CharField(choices=[('INCH', 'INCH'), ('MM', 'MM')], max_length=128, verbose_name='Top Tube sheet Thickness'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='total_tube_length',
            field=models.CharField(choices=[('INCH', 'INCH'), ('MM', 'MM')], max_length=128, verbose_name='Total Tube Length'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='tube_id',
            field=models.CharField(blank=True, choices=[('INCH', 'INCH'), ('MM', 'MM')], max_length=128, verbose_name='Tube ID'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='tube_protude_out_of_bottom_tube_sheet',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=128, verbose_name='Tube Protude Out Of Bottom Tube Sheet'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='tube_protude_out_of_top_tube_sheet',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=128, verbose_name='Tube Protude Out Of Top Tube Sheet'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='tube_spacing_or_pitch',
            field=models.CharField(choices=[('INCH', 'INCH'), ('MM', 'MM')], max_length=128, verbose_name='Tube Spacing Or Pitch'),
        ),
    ]
