# Generated by Django 4.1.1 on 2022-12-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0109_alter_reactor_bottom_tube_sheet_thickness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactor',
            name='tube_id',
            field=models.CharField(choices=[('INCH', 'INCH'), ('MM', 'MM')], max_length=128, verbose_name='Tube ID'),
        ),
    ]
