# Generated by Django 4.1.1 on 2022-12-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0111_remove_reactor_inch_remove_reactor_mm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactor',
            name='inch1',
        ),
        migrations.RemoveField(
            model_name='reactor',
            name='inch2',
        ),
        migrations.RemoveField(
            model_name='reactor',
            name='inch3',
        ),
        migrations.RemoveField(
            model_name='reactor',
            name='inch4',
        ),
        migrations.RemoveField(
            model_name='reactor',
            name='inch5',
        ),
        migrations.RemoveField(
            model_name='reactor',
            name='inch6',
        ),
        migrations.RemoveField(
            model_name='reactor',
            name='inch7',
        ),
        migrations.RemoveField(
            model_name='reactor',
            name='inch8',
        ),
        migrations.RemoveField(
            model_name='reactor',
            name='mm1',
        ),
        migrations.RemoveField(
            model_name='reactor',
            name='mm2',
        ),
        migrations.RemoveField(
            model_name='reactor',
            name='mm3',
        ),
        migrations.RemoveField(
            model_name='reactor',
            name='mm4',
        ),
        migrations.RemoveField(
            model_name='reactor',
            name='mm5',
        ),
        migrations.RemoveField(
            model_name='reactor',
            name='mm6',
        ),
        migrations.RemoveField(
            model_name='reactor',
            name='mm7',
        ),
        migrations.RemoveField(
            model_name='reactor',
            name='mm8',
        ),
        migrations.AddField(
            model_name='reactor',
            name='input_bottomtube',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='INCH/MM'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='input_ferruleid',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='INCH/MM'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='input_ferrulelength',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='INCH/MM'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='input_toptube',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='INCH/MM'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='input_totaltube',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='INCH/MM'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='input_tubeprotude_bottom',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='INCH/MM'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='input_tubeprotude_top',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='INCH/MM'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='input_tubespacing',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='INCH/MM'),
        ),
    ]
