# Generated by Django 4.1.1 on 2022-12-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0112_remove_reactor_inch1_remove_reactor_inch2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Accepted'), (0, 'Rejected')], default=0)),
                ('reason_reject', models.CharField(blank=True, max_length=50, verbose_name='reason for rejection')),
            ],
        ),
    ]
