# Generated by Django 4.1.1 on 2022-12-09 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0113_leave'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
