# Generated by Django 4.1.1 on 2022-12-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0114_delete_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactor',
            name='select_tube_protude_bottom',
            field=models.CharField(choices=[('INCH', 'INCH'), ('MM', 'MM')], default='', max_length=128, verbose_name='Select INCH Or MM'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='select_tube_protude_top',
            field=models.CharField(choices=[('INCH', 'INCH'), ('MM', 'MM')], default='', max_length=128, verbose_name='Select INCH Or MM'),
        ),
    ]
