# Generated by Django 4.1.1 on 2023-01-27 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "client",
            "0116_alter_client_alternate_name_alter_client_comman_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reactor",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactorunit+",
                to="client.unit",
            ),
        ),
    ]
