# Generated by Django 3.2.16 on 2023-02-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0117_alter_reactor_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactor',
            name='input_bottomtube',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=999, null=True, verbose_name='INCH/MM'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='input_ferruleid',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=999, null=True, verbose_name='INCH/MM'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='input_ferrulelength',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=999, null=True, verbose_name='INCH/MM'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='input_toptube',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=999, null=True, verbose_name='INCH/MM'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='input_totaltube',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=999, null=True, verbose_name='INCH/MM'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='input_tubeid',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=999, null=True, verbose_name='INCH/MM'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='input_tubeprotude_bottom',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=999, null=True, verbose_name='INCH/MM'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='input_tubeprotude_top',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=999, null=True, verbose_name='INCH/MM'),
        ),
    ]
