# Generated by Django 3.2.16 on 2023-02-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0118_auto_20230206_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactor',
            name='input_tubespacing',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=999, null=True, verbose_name='INCH/MM'),
        ),
    ]
