# Generated by Django 3.2.16 on 2023-02-10 05:29

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0119_alter_reactor_input_tubespacing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='official_address',
            field=models.ManyToManyField(blank=True, related_name='official_address', to='client.Address', verbose_name='Official Adrress'),
        ),
        migrations.AlterField(
            model_name='client',
            name='official_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='plantentrance_address',
            field=models.ManyToManyField(blank=True, related_name='plantentrance_address', to='client.Address', verbose_name='Plant Entrance Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='shipping_address',
            field=models.ManyToManyField(blank=True, related_name='shipping_address', to='client.Address', verbose_name='Shipping Address'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientplant+', to='client.client'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientunit+', to='client.client'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='plant',
            field=smart_selects.db_fields.GroupedForeignKey(blank=True, default='', group_field='client', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unitplant', to='client.plant'),
        ),
    ]
