# Generated by Django 3.2.16 on 2023-02-28 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0121_auto_20230210_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactor',
            name='bottom_tube_sheet_thickness',
            field=models.CharField(blank=True, choices=[('INCH', 'INCH'), ('MM', 'MM')], max_length=128, null=True, verbose_name='Bottom Tube Sheet Thickness Unit'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='dom_material',
            field=models.CharField(blank=True, max_length=128, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='DOM'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='ferrule_id',
            field=models.CharField(blank=True, choices=[('INCH', 'INCH'), ('MM', 'MM')], max_length=128, null=True, verbose_name='Ferrule ID unit'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='ferrule_length',
            field=models.CharField(blank=True, choices=[('INCH', 'INCH'), ('MM', 'MM')], max_length=128, null=True, verbose_name='Ferrule length unit'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='input_bottomtube',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=999, null=True, verbose_name='Bottom Tube Sheet Thickness Value'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='input_ferruleid',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=999, null=True, verbose_name='Ferrule ID Value'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='input_ferrulelength',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=999, null=True, verbose_name='ferrule length value'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='input_toptube',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=999, null=True, verbose_name='Top Tube Sheet Thickness Value'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='input_totaltube',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=999, null=True, verbose_name='Total Tube Length Value'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='input_tubeid',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=999, null=True, verbose_name='Tube ID value'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='input_tubeprotude_bottom',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=999, null=True, verbose_name='Tube Protude Out Of Bottom Tube Sheet Value'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='input_tubeprotude_top',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=999, null=True, verbose_name='Tube Protude Top Value'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='input_tubespacing',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=999, null=True, verbose_name='Tube Spacing or Pitch Value'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='select_tube_protude_bottom',
            field=models.CharField(blank=True, choices=[('INCH', 'INCH'), ('MM', 'MM')], default='', max_length=128, null=True, verbose_name='Tube Protude Out Of Bottom Tube Sheet Unit'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='select_tube_protude_top',
            field=models.CharField(blank=True, choices=[('INCH', 'INCH'), ('MM', 'MM')], default='', max_length=128, null=True, verbose_name='Tube Protude Top Unit'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='top_tube_sheet_thickness',
            field=models.CharField(blank=True, choices=[('INCH', 'INCH'), ('MM', 'MM')], max_length=128, null=True, verbose_name='Top Tube Sheet Thickness Unit'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='total_tube_length',
            field=models.CharField(blank=True, choices=[('INCH', 'INCH'), ('MM', 'MM')], max_length=128, null=True, verbose_name='Total Tube Length Unit'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='tube_id',
            field=models.CharField(blank=True, choices=[('INCH', 'INCH'), ('MM', 'MM')], max_length=128, null=True, verbose_name='Tube ID unit'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='tube_spacing_or_pitch',
            field=models.CharField(blank=True, choices=[('INCH', 'INCH'), ('MM', 'MM')], max_length=128, null=True, verbose_name='Tube Spacing or Pitch Unit'),
        ),
    ]
