# Generated by Django 3.2.16 on 2023-03-02 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0122_auto_20230228_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactor',
            name='dom_material',
            field=models.CharField(blank=True, max_length=128, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='DOME'),
        ),
        migrations.AlterField(
            model_name='reactor',
            name='top_dome_removable',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=128, null=True, verbose_name='Top Dome Removable'),
        ),
    ]
