# Generated by Django 3.2.16 on 2023-04-24 08:41

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0123_auto_20230302_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2, null=True),
        ),
    ]
