# Generated by Django 3.2.16 on 2023-04-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0124_client_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactor',
            name='MSDS',
            field=models.FileField(blank=True, null=True, upload_to='MSDS_files/'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='catalyst_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='reactor',
            name='catalyst_to_be_loaded',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='reactor',
            name='crush_strength',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='reactor',
            name='height',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='reactor',
            name='inner_diameter',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='reactor',
            name='layers_of_catalyst',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='reactor',
            name='layers_of_inerts',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='reactor',
            name='length',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='reactor',
            name='loaded_tube_length_in',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='reactor',
            name='loaded_tube_length_mm',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='reactor',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='reactor',
            name='model_number',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='reactor',
            name='outer_diameter',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='reactor',
            name='shape',
            field=models.CharField(blank=True, choices=[('TQ', 'TQ'), ('TABLET', 'TABLET'), ('EXTRADIET', 'EXTRADIET'), ('CYLINDER', 'CYLINDER'), ('PENTERING_CYLINDER', 'PENTERING_CYLINDER'), ('SPHERE', 'SPHERE'), ('OTHER', 'OTHER')], default='TQ', max_length=20),
        ),
        migrations.AddField(
            model_name='reactor',
            name='spring_drawing',
            field=models.FileField(blank=True, null=True, upload_to='spring_drawing/'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='spring_height',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='reactor',
            name='top_spring',
            field=models.BooleanField(blank=True, choices=[(True, 'yes'), (False, 'No')], default='True', verbose_name='top_spring'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='tube_bottom_retainer',
            field=models.CharField(blank=True, choices=[('SPRING', 'SPRING'), ('WIREMESH', 'WIREMESH'), ('OTHER', 'OTHER')], default='SPRING', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reactor',
            name='tube_loading_profile_drawing',
            field=models.FileField(blank=True, null=True, upload_to='tube_loading_profile_drawings/', verbose_name='Tube Loading Profile Drawings'),
        ),
        migrations.AddField(
            model_name='reactor',
            name='width',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
