# Generated by Django 3.2.16 on 2023-07-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0128_auto_20230427_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='official_name',
            field=models.CharField(blank=True, max_length=128, unique=True, verbose_name='Client Name'),
        ),
    ]
