# Generated by Django 3.2.16 on 2023-09-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0131_alter_reactor_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='official_name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(default='sds', max_length=500),
            preserve_default=False,
        ),
    ]
