# Generated by Django 3.2.16 on 2023-09-14 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tube', '0001_initial'),
        ('part', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(blank=True, max_length=128)),
                ('alternate_name', models.CharField(blank=True, max_length=128, verbose_name='Alternate Name')),
                ('serial_number', models.CharField(max_length=128, verbose_name='Serial Number')),
                ('asset_number', models.CharField(blank=True, max_length=128, verbose_name='Asset Number')),
                ('pm_status', models.CharField(blank=True, choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], max_length=20, null=True, verbose_name='PM Status')),
                ('remarks', models.CharField(blank=True, max_length=999, null=True)),
                ('location_for_storage', models.CharField(blank=True, max_length=128, verbose_name='Location For Storage')),
                ('packaging', models.CharField(blank=True, max_length=128)),
                ('is_this_part_of_set', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=128, null=True, verbose_name='Is This Part Of Set?')),
                ('if_yes_how_many_in_a_set', models.CharField(blank=True, max_length=128, verbose_name='If Yes How Many In A Set?')),
                ('frame', models.CharField(blank=True, max_length=128)),
                ('image', models.ImageField(blank=True, default='', upload_to='uploads/bdd/')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('BDD_tube_seal_rack', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bdd', to='part.bdd_tube_seal_rack', verbose_name='BDD Tube Seal Rack')),
                ('location_for_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bdd', to='tube.warehouse', verbose_name='Location For Warehouse')),
            ],
            options={
                'verbose_name': 'BDD',
            },
        ),
        migrations.CreateModel(
            name='CALIBRATION_STAND',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(blank=True, max_length=128)),
                ('alternate_name', models.CharField(blank=True, max_length=128, verbose_name='Alternate Name')),
                ('serial_number', models.CharField(blank=True, max_length=128, verbose_name='Serial Number')),
                ('asset_number', models.CharField(blank=True, max_length=128, verbose_name='Asset Number')),
                ('pm_status', models.CharField(blank=True, choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], max_length=20, null=True, verbose_name='PM Status')),
                ('remarks', models.CharField(blank=True, max_length=999, null=True)),
                ('location_for_storage', models.CharField(blank=True, max_length=128, verbose_name='Location For Storage')),
                ('packaging', models.CharField(blank=True, max_length=128)),
                ('is_this_part_of_set', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=128, verbose_name='Is This Part Of Set?')),
                ('if_yes_how_many_in_a_set', models.CharField(blank=True, max_length=128, verbose_name='If Yes How Many In A Set?')),
                ('cal_stand_size', models.CharField(blank=True, max_length=128, verbose_name='Calibration Stand Size')),
                ('frame', models.CharField(blank=True, max_length=128)),
                ('image', models.ImageField(blank=True, default='', upload_to='uploads/cal_stand/')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('calibration_orifice_set', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibration', to='part.calibration_orifice', verbose_name='Calibration Orifice Set')),
                ('location_for_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibration_stand', to='tube.warehouse', verbose_name='Location For Warehouse')),
            ],
            options={
                'verbose_name': 'Calibration Rack',
            },
        ),
        migrations.CreateModel(
            name='TTD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(blank=True, max_length=128, null=True)),
                ('alternate_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Alternate Name')),
                ('serial_number', models.CharField(max_length=128, verbose_name='Serial Number')),
                ('asset_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='Asset Number')),
                ('pm_status', models.CharField(blank=True, choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], max_length=20, null=True, verbose_name='PM Status')),
                ('remarks', models.CharField(blank=True, max_length=999, null=True)),
                ('location_for_storage', models.CharField(blank=True, max_length=128, verbose_name='Location For Storage')),
                ('packaging', models.CharField(blank=True, max_length=128)),
                ('is_this_part_of_set', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=128, null=True, verbose_name='Is This Part Of Set')),
                ('if_yes_how_many_in_a_set', models.CharField(blank=True, max_length=128, verbose_name='If Yes How Many In A Set?')),
                ('frame', models.CharField(blank=True, max_length=128)),
                ('image', models.ImageField(blank=True, default='', upload_to='uploads/ttd/')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('TTD_tube_seal_rack', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TTD', to='part.ttd_tube_seal_rack', verbose_name='TTD Tube Seal Rack')),
                ('location_for_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ttd', to='tube.warehouse', verbose_name='Location For Warehouse')),
                ('pressure_sensor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TTD', to='part.pressure_sensor', verbose_name='Pressure Sensor')),
                ('supply_orifice_set', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TTD', to='part.supply_orifice', verbose_name='Supply Orifice Set')),
            ],
            options={
                'verbose_name': 'TTD',
            },
        ),
        migrations.CreateModel(
            name='SwabMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_for_storage', models.CharField(blank=True, max_length=128, null=True, verbose_name='Location For Storage')),
                ('packaging', models.CharField(blank=True, max_length=128, null=True)),
                ('is_this_part_of_set', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=128, null=True, verbose_name='Is This Part Of Set')),
                ('if_yes_how_many_in_a_set', models.CharField(blank=True, max_length=128, verbose_name='If Yes How Many In A Set?')),
                ('abbreviation', models.CharField(blank=True, max_length=128, null=True)),
                ('alternate_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Alternate Name')),
                ('serial_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='Serial Number')),
                ('asset_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='Asset Number')),
                ('pm_status', models.CharField(blank=True, choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], max_length=20, null=True, verbose_name='PM Status')),
                ('remarks', models.CharField(blank=True, max_length=999, null=True)),
                ('Generation_1', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True)),
                ('Generation_2', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('Swab_Master_Tube_Seal_Rack', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swabmaster', to='part.swabmastertsr', verbose_name='SwabMaster Tube Seal Rack')),
                ('location_for_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swabmaster', to='tube.warehouse', verbose_name='Location For Warehouse')),
            ],
            options={
                'verbose_name': 'Swab Master',
            },
        ),
        migrations.CreateModel(
            name='EquipmentCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.bdd')),
                ('calibratopn_stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.calibration_stand')),
                ('swabmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.swabmaster')),
                ('ttd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.ttd')),
            ],
        ),
    ]
