# Generated by Django 4.1.1 on 2022-10-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttd',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ttd',
            name='allow_to_add_sub_parts',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ttd',
            name='alternate_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ttd',
            name='asset_number',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ttd',
            name='if_yes_how_many_in_a_set',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ttd',
            name='is_it_an_assembly',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ttd',
            name='is_this_part_of_set',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ttd',
            name='location_for_storage',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ttd',
            name='location_for_warehouse',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ttd',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ttd',
            name='packaging',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ttd',
            name='pm_status',
            field=models.CharField(choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], default='RED', max_length=20),
        ),
        migrations.AddField(
            model_name='ttd',
            name='serial_number',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
