# Generated by Django 3.2.16 on 2023-09-18 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0001_initial'),
        ('equipment', '0002_alter_bdd_bdd_tube_seal_rack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration_stand',
            name='calibration_orifice_set',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibration', to='part.calibration_orifice', verbose_name='Calibration Orifice Set'),
        ),
    ]
