# Generated by Django 4.1.1 on 2022-10-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_bdd_abbreviation_bdd_allow_to_add_sub_parts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdd',
            name='is_it_an_assembly',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=128),
        ),
        migrations.AlterField(
            model_name='bdd',
            name='is_this_part_of_set',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=128),
        ),
        migrations.AlterField(
            model_name='calibration_stand',
            name='is_it_an_assembly',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=128),
        ),
        migrations.AlterField(
            model_name='calibration_stand',
            name='is_this_part_of_set',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=128),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='is_it_an_assembly',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=128),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='is_this_part_of_set',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=128),
        ),
    ]
