# Generated by Django 4.1.1 on 2022-10-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_alter_bdd_is_it_an_assembly_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bdd',
            name='BDD_SN',
        ),
        migrations.RemoveField(
            model_name='ttd',
            name='TTD_SN',
        ),
        migrations.RemoveField(
            model_name='bdd',
            name='allow_to_add_sub_parts',
        ),
        migrations.RemoveField(
            model_name='calibration_stand',
            name='allow_to_add_sub_parts',
        ),
        migrations.RemoveField(
            model_name='ttd',
            name='allow_to_add_sub_parts',
        ),
        migrations.AddField(
            model_name='bdd',
            name='allow_to_add_sub_parts',
            field=models.ManyToManyField(to='equipment.part', verbose_name='Allowed To Add Sub Parts'),
        ),
        migrations.AddField(
            model_name='calibration_stand',
            name='allow_to_add_sub_parts',
            field=models.ManyToManyField(to='equipment.part', verbose_name='Allowed To Add Sub Parts'),
        ),
        migrations.AddField(
            model_name='ttd',
            name='allow_to_add_sub_parts',
            field=models.ManyToManyField(to='equipment.part', verbose_name='Allowed To Add Sub Parts'),
        ),
    ]
