# Generated by Django 4.1.1 on 2022-10-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_remove_bdd_bdd_sn_remove_ttd_ttd_sn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bdd',
            name='name',
        ),
        migrations.RemoveField(
            model_name='calibration_stand',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ttd',
            name='name',
        ),
    ]
