# Generated by Django 4.1.1 on 2022-10-19 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_remove_bdd_allow_to_add_sub_parts_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pressure_senser',
            new_name='Pressure_sensor',
        ),
        migrations.RenameField(
            model_name='ttd',
            old_name='pressure_senser',
            new_name='pressure_sensor',
        ),
    ]
