# Generated by Django 4.1.1 on 2022-10-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0005_remove_bdd_bdd_tube_seal_rack_and_more'),
        ('equipment', '0010_delete_part_remove_bdd_bdd_tube_seal_rack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttd',
            name='warehouse_location',
            field=models.ManyToManyField(default='', to='tube.warehouse', verbose_name='Warehouse Location'),
        ),
    ]
