# Generated by Django 4.1.1 on 2022-10-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0001_initial'),
        ('tube', '0005_remove_bdd_bdd_tube_seal_rack_and_more'),
        ('equipment', '0011_ttd_warehouse_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttd',
            name='warehouse_location',
        ),
        migrations.AddField(
            model_name='ttd',
            name='TTD_tube_seal_rack',
            field=models.ManyToManyField(to='part.ttd_tube_seal_rack'),
        ),
        migrations.AddField(
            model_name='ttd',
            name='pressure_sensor',
            field=models.ManyToManyField(to='part.pressure_sensor'),
        ),
        migrations.AddField(
            model_name='ttd',
            name='supply_orifice_set',
            field=models.ManyToManyField(to='part.supply_orifice'),
        ),
        migrations.RemoveField(
            model_name='bdd',
            name='location_for_warehouse',
        ),
        migrations.RemoveField(
            model_name='calibration_stand',
            name='location_for_warehouse',
        ),
        migrations.RemoveField(
            model_name='ttd',
            name='location_for_warehouse',
        ),
        migrations.AddField(
            model_name='bdd',
            name='location_for_warehouse',
            field=models.ManyToManyField(default='', null=True, to='tube.warehouse', verbose_name='Warehouse Location'),
        ),
        migrations.AddField(
            model_name='calibration_stand',
            name='location_for_warehouse',
            field=models.ManyToManyField(default='', to='tube.warehouse', verbose_name='Warehouse Location'),
        ),
        migrations.AddField(
            model_name='ttd',
            name='location_for_warehouse',
            field=models.ManyToManyField(default='', to='tube.warehouse', verbose_name='Warehouse Location'),
        ),
    ]
