# Generated by Django 4.1.1 on 2022-10-20 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0005_remove_bdd_bdd_tube_seal_rack_and_more'),
        ('equipment', '0012_remove_ttd_warehouse_location_ttd_ttd_tube_seal_rack_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttd',
            name='location_for_warehouse',
        ),
        migrations.AddField(
            model_name='ttd',
            name='location_for_warehouse',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='tube.warehouse', verbose_name='Warehouse Location'),
        ),
    ]
