# Generated by Django 4.1.1 on 2022-10-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0014_bdd_bdd_tube_seal_rack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdd',
            name='frame',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='calibration_stand',
            name='frame',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ttd',
            name='frame',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
