# Generated by Django 4.1.1 on 2022-10-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0015_bdd_frame_calibration_stand_frame_ttd_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdd',
            name='image',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='calibration_stand',
            name='image',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='ttd',
            name='image',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
    ]
