# Generated by Django 4.1.1 on 2022-10-20 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0005_remove_bdd_bdd_tube_seal_rack_and_more'),
        ('equipment', '0016_bdd_image_calibration_stand_image_ttd_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdd',
            name='location_for_warehouse',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='tube.warehouse', verbose_name='Warehouse Location'),
        ),
        migrations.AlterField(
            model_name='bdd',
            name='pm_status',
            field=models.CharField(blank=True, choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], default='RED', max_length=20),
        ),
        migrations.AlterField(
            model_name='calibration_stand',
            name='location_for_warehouse',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='tube.warehouse', verbose_name='Warehouse Location'),
        ),
        migrations.AlterField(
            model_name='calibration_stand',
            name='pm_status',
            field=models.CharField(blank=True, choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], default='RED', max_length=20),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='location_for_warehouse',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='tube.warehouse', verbose_name='Warehouse Location'),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='pm_status',
            field=models.CharField(blank=True, choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], default='RED', max_length=20),
        ),
    ]
