# Generated by Django 4.1.1 on 2022-12-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0021_alter_bdd_image_alter_calibration_stand_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdd',
            name='is_this_part_of_set',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=128),
        ),
        migrations.AlterField(
            model_name='bdd',
            name='pm_status',
            field=models.CharField(choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='calibration_stand',
            name='is_this_part_of_set',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=128),
        ),
        migrations.AlterField(
            model_name='calibration_stand',
            name='pm_status',
            field=models.CharField(choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='is_this_part_of_set',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=128),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='pm_status',
            field=models.CharField(choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], max_length=20),
        ),
    ]
