# Generated by Django 4.1.1 on 2022-12-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0011_remove_part_part_image'),
        ('equipment', '0025_alter_bdd_bdd_tube_seal_rack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdd',
            name='BDD_tube_seal_rack',
            field=models.ManyToManyField(blank=True, to='part.bdd_tube_seal_rack', verbose_name='BDD Tube Seal Rack'),
        ),
        migrations.AlterField(
            model_name='calibration_stand',
            name='calibration_orifice_set',
            field=models.ManyToManyField(blank=True, to='part.calibration_orifice', verbose_name='Calibration Orifice Set'),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='TTD_tube_seal_rack',
            field=models.ManyToManyField(blank=True, to='part.ttd_tube_seal_rack', verbose_name='TTD Tube Seal Rack'),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='pressure_sensor',
            field=models.ManyToManyField(blank=True, to='part.pressure_sensor', verbose_name='Pressure Sensor'),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='supply_orifice_set',
            field=models.ManyToManyField(blank=True, to='part.supply_orifice', verbose_name='Supply Orifice Set'),
        ),
    ]
