# Generated by Django 4.1.1 on 2022-12-12 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0011_remove_part_part_image'),
        ('equipment', '0026_alter_bdd_bdd_tube_seal_rack_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bdd',
            name='BDD_tube_seal_rack',
        ),
        migrations.RemoveField(
            model_name='calibration_stand',
            name='calibration_orifice_set',
        ),
        migrations.RemoveField(
            model_name='ttd',
            name='TTD_tube_seal_rack',
        ),
        migrations.RemoveField(
            model_name='ttd',
            name='pressure_sensor',
        ),
        migrations.RemoveField(
            model_name='ttd',
            name='supply_orifice_set',
        ),
        migrations.AddField(
            model_name='bdd',
            name='BDD_tube_seal_rack',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='part.bdd_tube_seal_rack', verbose_name='BDD Tube Seal Rack'),
        ),
        migrations.AddField(
            model_name='calibration_stand',
            name='calibration_orifice_set',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='part.calibration_orifice', verbose_name='Calibration Orifice Set'),
        ),
        migrations.AddField(
            model_name='ttd',
            name='TTD_tube_seal_rack',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='part.ttd_tube_seal_rack', verbose_name='TTD Tube Seal Rack'),
        ),
        migrations.AddField(
            model_name='ttd',
            name='pressure_sensor',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='part.pressure_sensor', verbose_name='Pressure Sensor'),
        ),
        migrations.AddField(
            model_name='ttd',
            name='supply_orifice_set',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='part.supply_orifice', verbose_name='Supply Orifice Set'),
        ),
    ]
