# Generated by Django 3.2.16 on 2023-02-06 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0005_remove_bdd_bdd_tube_seal_rack_and_more'),
        ('equipment', '0027_remove_bdd_bdd_tube_seal_rack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdd',
            name='location_for_warehouse',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.warehouse', verbose_name='Location For Warehouse'),
        ),
        migrations.AlterField(
            model_name='calibration_stand',
            name='location_for_warehouse',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tube.warehouse', verbose_name='Location For Warehouse'),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='location_for_warehouse',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tube.warehouse', verbose_name='Location For Warehouse'),
        ),
    ]
