# Generated by Django 3.2.16 on 2023-02-06 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0022_auto_20230206_1244'),
        ('equipment', '0028_auto_20230206_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdd',
            name='BDD_tube_seal_rack',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='bdd', to='part.bdd_tube_seal_rack', verbose_name='BDD Tube Seal Rack'),
        ),
        migrations.AlterField(
            model_name='calibration_stand',
            name='calibration_orifice_set',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='calibration', to='part.calibration_orifice', verbose_name='Calibration Orifice Set'),
        ),
        migrations.AlterField(
            model_name='calibration_stand',
            name='is_this_part_of_set',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=128, verbose_name='Is This Part Of Set?'),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='TTD_tube_seal_rack',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='ttd', to='part.ttd_tube_seal_rack', verbose_name='TTD Tube Seal Rack'),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='pressure_sensor',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='ttd', to='part.pressure_sensor', verbose_name='Pressure Sensor'),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='supply_orifice_set',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='ttd', to='part.supply_orifice', verbose_name='Supply Orifice Set'),
        ),
    ]
