# Generated by Django 3.2.16 on 2023-02-07 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0022_auto_20230206_1244'),
        ('equipment', '0029_auto_20230206_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttd',
            name='TTD_tube_seal_rack',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ttd', to='part.ttd_tube_seal_rack', verbose_name='TTD Tube Seal Rack'),
        ),
    ]
