# Generated by Django 3.2.16 on 2023-02-07 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0022_auto_20230206_1244'),
        ('equipment', '0030_alter_ttd_ttd_tube_seal_rack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttd',
            name='pressure_sensor',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ttd', to='part.pressure_sensor', verbose_name='Pressure Sensor'),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='supply_orifice_set',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ttd', to='part.supply_orifice', verbose_name='Supply Orifice Set'),
        ),
    ]
