# Generated by Django 3.2.16 on 2023-02-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0031_auto_20230207_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwabMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
