# Generated by Django 3.2.16 on 2023-02-07 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0032_swabmaster'),
        ('part', '0023_airhoses_devicehoses_swabmaster_tsr'),
    ]

    operations = [
        migrations.AddField(
            model_name='swabmaster',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='part.swabmaster_tsr', verbose_name='SwabMaster Tube Seal Rack'),
        ),
    ]
