# Generated by Django 3.2.16 on 2023-02-07 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0033_swabmaster_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calibration_stand',
            options={'verbose_name': 'Calibration Rack'},
        ),
    ]
