# Generated by Django 3.2.16 on 2023-02-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0034_alter_calibration_stand_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swabmaster',
            old_name='name',
            new_name='Swab_Master_Tube_Seal_Rack',
        ),
        migrations.AddField(
            model_name='swabmaster',
            name='Generation_1',
            field=models.CharField(blank=True, choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='swabmaster',
            name='Generation_2',
            field=models.CharField(blank=True, choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='swabmaster',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='swabmaster',
            name='alternate_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Alternate Name'),
        ),
        migrations.AddField(
            model_name='swabmaster',
            name='asset_number',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Asset Number'),
        ),
        migrations.AddField(
            model_name='swabmaster',
            name='if_yes_how_many_in_a_set',
            field=models.CharField(blank=True, max_length=128, verbose_name='If Yes How Many In A Set?'),
        ),
        migrations.AddField(
            model_name='swabmaster',
            name='is_this_part_of_set',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default=1, max_length=128, verbose_name='Is This Part Of Set'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swabmaster',
            name='location_for_storage',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Location For Storage'),
        ),
        migrations.AddField(
            model_name='swabmaster',
            name='packaging',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='swabmaster',
            name='pm_status',
            field=models.CharField(choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], default=1, max_length=20, verbose_name='PM Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swabmaster',
            name='serial_number',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Serial Number'),
        ),
    ]
