# Generated by Django 3.2.16 on 2023-02-09 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0005_remove_bdd_bdd_tube_seal_rack_and_more'),
        ('equipment', '0035_auto_20230209_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='swabmaster',
            name='location_for_warehouse',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tube.warehouse', verbose_name='Location For Warehouse'),
        ),
    ]
