# Generated by Django 3.2.16 on 2023-02-09 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0026_alter_pressure_sensor_options'),
        ('equipment', '0036_swabmaster_location_for_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdd',
            name='is_this_part_of_set',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=128, null=True, verbose_name='Is This Part Of Set?'),
        ),
        migrations.AlterField(
            model_name='bdd',
            name='pm_status',
            field=models.CharField(blank=True, choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], max_length=20, null=True, verbose_name='PM Status'),
        ),
        migrations.AlterField(
            model_name='swabmaster',
            name='Generation_1',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='swabmaster',
            name='Generation_2',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='swabmaster',
            name='Swab_Master_Tube_Seal_Rack',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='part.swabmastertsr', verbose_name='SwabMaster Tube Seal Rack'),
        ),
        migrations.AlterField(
            model_name='swabmaster',
            name='pm_status',
            field=models.CharField(blank=True, choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], max_length=20, null=True, verbose_name='PM Status'),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='alternate_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Alternate Name'),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='asset_number',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Asset Number'),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='is_this_part_of_set',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=128, null=True, verbose_name='Is This Part Of Set'),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='pm_status',
            field=models.CharField(blank=True, choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], max_length=20, null=True, verbose_name='PM Status'),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='serial_number',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Serial Number'),
        ),
    ]
