# Generated by Django 3.2.16 on 2023-02-09 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0026_alter_pressure_sensor_options'),
        ('equipment', '0037_auto_20230209_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdd',
            name='BDD_tube_seal_rack',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bdd', to='part.bdd_tube_seal_rack', verbose_name='BDD Tube Seal Rack'),
        ),
    ]
