# Generated by Django 3.2.16 on 2023-02-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0039_auto_20230209_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdd',
            name='remarks',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='calibration_stand',
            name='remarks',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='swabmaster',
            name='remarks',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='remarks',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
