# Generated by Django 3.2.16 on 2023-02-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0040_auto_20230209_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bdd',
            options={'verbose_name': 'BDD'},
        ),
        migrations.AlterModelOptions(
            name='swabmaster',
            options={'verbose_name': 'Swab Master'},
        ),
        migrations.AlterModelOptions(
            name='ttd',
            options={'verbose_name': 'TTD'},
        ),
        migrations.AlterField(
            model_name='swabmaster',
            name='Generation_1',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='swabmaster',
            name='Generation_2',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='swabmaster',
            name='is_this_part_of_set',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=128, null=True, verbose_name='Is This Part Of Set'),
        ),
    ]
