# Generated by Django 3.2.16 on 2023-02-10 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0006_auto_20230210_1132'),
        ('equipment', '0042_alter_swabmaster_location_for_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swabmaster',
            name='location_for_warehouse',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tube.warehouse', verbose_name='Location For Warehouse'),
        ),
    ]
