# Generated by Django 3.2.16 on 2023-02-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0042_alter_calibration_stand_calibration_orifice_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration_stand',
            name='is_this_part_of_set',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=128, verbose_name='Is This Part Of Set?'),
        ),
    ]
