# Generated by Django 3.2.16 on 2023-02-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0043_alter_calibration_stand_is_this_part_of_set'),
        ('equipment', '0043_alter_swabmaster_location_for_warehouse'),
    ]

    operations = [
    ]
