# Generated by Django 3.2.16 on 2023-02-28 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0032_alter_bdd_tube_seal_rack_number_of_tubes'),
        ('equipment', '0044_merge_20230213_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttd',
            name='supply_orifice_set',
            field=models.OneToOneField(blank=True, default='', limit_choices_to={'TTD__supply_orifice_set__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TTD', to='part.supply_orifice', verbose_name='Supply Orifice Set'),
        ),
    ]
