# Generated by Django 3.2.16 on 2023-03-14 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0033_auto_20230314_0519'),
        ('equipment', '0045_alter_ttd_supply_orifice_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swabmaster',
            name='Swab_Master_Tube_Seal_Rack',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swabmaster', to='part.swabmastertsr', verbose_name='SwabMaster Tube Seal Rack'),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='TTD_tube_seal_rack',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TTD', to='part.ttd_tube_seal_rack', verbose_name='TTD Tube Seal Rack'),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='pressure_sensor',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TTD', to='part.pressure_sensor', verbose_name='Pressure Sensor'),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='supply_orifice_set',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TTD', to='part.supply_orifice', verbose_name='Supply Orifice Set'),
        ),
    ]
