# Generated by Django 3.2.16 on 2023-07-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0048_equipmentcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttd',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
