# Generated by Django 3.2.16 on 2023-07-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0049_ttd_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttd',
            name='alternate_name',
            field=models.CharField(default='Alternate', max_length=128, verbose_name='Alternate Name'),
            preserve_default=False,
        ),
    ]
