# Generated by Django 3.2.16 on 2023-07-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0050_alter_ttd_alternate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttd',
            name='alternate_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Alternate Name'),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='serial_number',
            field=models.CharField(default='bbdbd211', max_length=128, verbose_name='Serial Number'),
            preserve_default=False,
        ),
    ]
