# Generated by Django 3.2.16 on 2023-07-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0051_auto_20230705_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdd',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='calibration_stand',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='swabmaster',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bdd',
            name='serial_number',
            field=models.CharField(max_length=128, verbose_name='Serial Number'),
        ),
    ]
