# Generated by Django 3.2.16 on 2023-09-07 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0016_alter_warehouse_warehouse_name'),
        ('part', '0047_auto_20230907_1607'),
        ('equipment', '0052_auto_20230705_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdd',
            name='BDD_tube_seal_rack',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bdd', to='part.bdd_tube_seal_rack', verbose_name='BDD Tube Seal Rack'),
        ),
        migrations.AlterField(
            model_name='bdd',
            name='location_for_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bdd', to='tube.warehouse', verbose_name='Location For Warehouse'),
        ),
        migrations.AlterField(
            model_name='calibration_stand',
            name='calibration_orifice_set',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibration', to='part.calibration_orifice', verbose_name='Calibration Orifice Set'),
        ),
        migrations.AlterField(
            model_name='calibration_stand',
            name='location_for_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibration_stand', to='tube.warehouse', verbose_name='Location For Warehouse'),
        ),
        migrations.AlterField(
            model_name='swabmaster',
            name='Swab_Master_Tube_Seal_Rack',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swabmaster', to='part.swabmastertsr', verbose_name='SwabMaster Tube Seal Rack'),
        ),
        migrations.AlterField(
            model_name='swabmaster',
            name='location_for_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swabmaster', to='tube.warehouse', verbose_name='Location For Warehouse'),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='TTD_tube_seal_rack',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TTD', to='part.ttd_tube_seal_rack', verbose_name='TTD Tube Seal Rack'),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='location_for_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ttd', to='tube.warehouse', verbose_name='Location For Warehouse'),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='pressure_sensor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TTD', to='part.pressure_sensor', verbose_name='Pressure Sensor'),
        ),
        migrations.AlterField(
            model_name='ttd',
            name='supply_orifice_set',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TTD', to='part.supply_orifice', verbose_name='Supply Orifice Set'),
        ),
    ]
