# Generated by Django 4.1.1 on 2022-10-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BDD_tube_seal_rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=128)),
                ('qty_rack', models.CharField(blank=True, max_length=128)),
                ('tube_seal_rack', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Calibration_orifice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=128)),
                ('total_sets', models.CharField(blank=True, max_length=128)),
                ('in_sets', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(blank=True, max_length=128)),
                ('part_no', models.CharField(blank=True, max_length=128)),
                ('part_function', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pressure_sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.CharField(blank=True, max_length=128)),
                ('quantity', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Supply_orifice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=128)),
                ('total_sets', models.CharField(blank=True, max_length=128)),
                ('orifice_in_each_set', models.CharField(blank=True, max_length=128)),
                ('storage_case', models.CharField(blank=True, max_length=128)),
                ('notes', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TTD_tube_seal_rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=128)),
                ('qty_rack', models.CharField(blank=True, max_length=128)),
                ('tube_seal_rack', models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
