# Generated by Django 4.1.1 on 2022-10-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='part_image',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
    ]
