# Generated by Django 3.2.16 on 2023-09-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0002_alter_supply_orifice_location_for_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airhose',
            name='breadth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airhose',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airhose',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airhose',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='bdd_tube_seal_rack',
            name='breadth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bdd_tube_seal_rack',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bdd_tube_seal_rack',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bdd_tube_seal_rack',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='calibration_orifice',
            name='breadth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calibration_orifice',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calibration_orifice',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calibration_orifice',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='devicehose',
            name='breadth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicehose',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicehose',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicehose',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='part',
            name='breadth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='pressure_sensor',
            name='breadth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pressure_sensor',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pressure_sensor',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pressure_sensor',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='supply_orifice',
            name='breadth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supply_orifice',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supply_orifice',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supply_orifice',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='swabmastertsr',
            name='breadth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swabmastertsr',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swabmastertsr',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swabmastertsr',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='ttd_tube_seal_rack',
            name='breadth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ttd_tube_seal_rack',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ttd_tube_seal_rack',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ttd_tube_seal_rack',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight'),
        ),
    ]
