# Generated by Django 4.1.1 on 2022-10-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0004_alter_part_part_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='post/thumbnail/%Y/%m/%d/'),
        ),
    ]
