# Generated by Django 4.1.1 on 2022-10-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0005_part_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
