# Generated by Django 4.1.1 on 2022-10-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0006_alter_part_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='thumbnail',
        ),
    ]
