# Generated by Django 4.1.1 on 2022-11-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0007_remove_part_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
