# Generated by Django 4.1.1 on 2022-11-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0008_alter_part_part_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
