# Generated by Django 4.1.1 on 2022-11-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0009_part_thumbnail_alter_part_part_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='thumbnail',
        ),
    ]
