# Generated by Django 4.1.1 on 2022-11-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0010_remove_part_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='part_image',
        ),
    ]
