# Generated by Django 4.1.1 on 2023-01-18 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0005_remove_bdd_bdd_tube_seal_rack_and_more'),
        ('part', '0011_remove_part_part_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='part_function',
            new_name='packaging',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='part_no',
            new_name='part_abbreviation',
        ),
        migrations.AddField(
            model_name='part',
            name='PM_STATUS',
            field=models.CharField(blank=True, choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green')], max_length=200),
        ),
        migrations.AddField(
            model_name='part',
            name='is_this_part_of_set',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default=1, max_length=128, verbose_name='Is This Part Of Set?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='it_is_an_assembly',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default=1, max_length=128, verbose_name='It is an assembly?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='part_alternate_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='part',
            name='part_asset_number',
            field=models.CharField(blank=True, max_length=128, verbose_name='Asset Number'),
        ),
        migrations.AddField(
            model_name='part',
            name='part_location_of_storage',
            field=models.CharField(blank=True, max_length=128, verbose_name='Location For Storage'),
        ),
        migrations.AddField(
            model_name='part',
            name='part_location_of_warehouse',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='tube.warehouse', verbose_name='Location For Warehouse'),
        ),
        migrations.AddField(
            model_name='part',
            name='part_serial_number',
            field=models.CharField(blank=True, max_length=128, verbose_name='Serial Number'),
        ),
    ]
