# Generated by Django 4.1.1 on 2023-01-18 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0005_remove_bdd_bdd_tube_seal_rack_and_more'),
        ('part', '0013_alter_part_packaging_alter_part_part_asset_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='PM_STATUS',
            field=models.CharField(blank=True, choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='is_this_part_of_set',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=128, null=True, verbose_name='Is This Part Of Set?'),
        ),
        migrations.AlterField(
            model_name='part',
            name='it_is_an_assembly',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=128, null=True, verbose_name='It is an assembly?'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_abbreviation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_alternate_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_asset_number',
            field=models.IntegerField(blank=True, max_length=128, null=True, verbose_name='Asset Number'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_location_of_warehouse',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='tube.warehouse', verbose_name='Location For Warehouse'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_serial_number',
            field=models.IntegerField(blank=True, max_length=128, null=True, verbose_name='Serial Number'),
        ),
    ]
