# Generated by Django 4.1.1 on 2023-01-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0016_alter_part_part_location_of_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='part_abbreviation',
        ),
        migrations.RemoveField(
            model_name='part',
            name='part_location_of_warehouse',
        ),
        migrations.AlterField(
            model_name='part',
            name='part_asset_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Asset Number'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_serial_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Serial Number'),
        ),
    ]
