# Generated by Django 3.2.16 on 2023-02-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0021_part_alternate_name_part_asset_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdd_tube_seal_rack',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='calibration_orifice',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pressure_sensor',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='supply_orifice',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ttd_tube_seal_rack',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
