# Generated by Django 3.2.16 on 2023-02-07 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0005_remove_bdd_bdd_tube_seal_rack_and_more'),
        ('part', '0022_auto_20230206_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwabMaster_TSR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('size', models.CharField(blank=True, max_length=128)),
                ('qty_rack', models.CharField(blank=True, max_length=128)),
                ('tube_seal_rack', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceHoses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField()),
                ('colour_code', models.CharField(max_length=50)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='AirHoses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField()),
                ('length', models.DecimalField(decimal_places=3, max_digits=999)),
                ('colour_code', models.CharField(max_length=50)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tube.warehouse')),
            ],
        ),
    ]
