# Generated by Django 3.2.16 on 2023-02-07 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0033_swabmaster_name'),
        ('tube', '0005_remove_bdd_bdd_tube_seal_rack_and_more'),
        ('part', '0023_airhoses_devicehoses_swabmaster_tsr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AirHoses',
            new_name='AirHose',
        ),
        migrations.RenameModel(
            old_name='DeviceHoses',
            new_name='DeviceHose',
        ),
        migrations.RenameModel(
            old_name='SwabMaster_TSR',
            new_name='SwabMasterTSR',
        ),
    ]
