# Generated by Django 3.2.16 on 2023-02-07 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0025_auto_20230207_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pressure_sensor',
            options={'verbose_name': 'Pressure Sensor'},
        ),
    ]
