# Generated by Django 3.2.16 on 2023-02-09 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0005_remove_bdd_bdd_tube_seal_rack_and_more'),
        ('part', '0026_alter_pressure_sensor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airhose',
            options={'verbose_name': 'Air Hose'},
        ),
        migrations.AlterField(
            model_name='airhose',
            name='colour_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='airhose',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=999, null=True),
        ),
        migrations.AlterField(
            model_name='airhose',
            name='serial_number',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='airhose',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.warehouse'),
        ),
        migrations.AlterField(
            model_name='devicehose',
            name='colour_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devicehose',
            name='serial_number',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='devicehose',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.warehouse'),
        ),
        migrations.AlterField(
            model_name='part',
            name='is_this_part_of_set',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='it_is_an_assembly',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='location_for_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.warehouse'),
        ),
        migrations.AlterField(
            model_name='part',
            name='pm_status',
            field=models.CharField(blank=True, choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], max_length=20, null=True),
        ),
    ]
