# Generated by Django 3.2.16 on 2023-02-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0027_auto_20230209_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'verbose_name': 'All General Part'},
        ),
    ]
