# Generated by Django 3.2.16 on 2023-02-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0028_alter_part_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicehose',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=999, null=True),
        ),
    ]
