# Generated by Django 3.2.16 on 2023-02-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0029_devicehose_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airhose',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
