# Generated by Django 3.2.16 on 2023-02-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0030_alter_airhose_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bdd_tube_seal_rack',
            name='qty_rack',
        ),
        migrations.RemoveField(
            model_name='bdd_tube_seal_rack',
            name='tube_seal_rack',
        ),
        migrations.AddField(
            model_name='bdd_tube_seal_rack',
            name='number_of_tubes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
