# Generated by Django 3.2.16 on 2023-02-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0031_auto_20230228_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdd_tube_seal_rack',
            name='number_of_tubes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
