# Generated by Django 3.2.16 on 2023-03-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0033_auto_20230314_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
