# Generated by Django 3.2.16 on 2023-03-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0034_part_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='images/general_parts'),
        ),
    ]
