# Generated by Django 3.2.16 on 2023-03-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0036_alter_part_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='dimension',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dimension'),
        ),
        migrations.AddField(
            model_name='part',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='part',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Weight'),
        ),
    ]
