# Generated by Django 3.2.16 on 2023-04-24 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0010_alter_warehouse_date_created'),
        ('part', '0037_auto_20230317_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdd_tube_seal_rack',
            name='location_for_warehouse',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.warehouse', verbose_name='Location For Warehouse'),
        ),
        migrations.AddField(
            model_name='calibration_orifice',
            name='location_for_warehouse',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.warehouse', verbose_name='Location For Warehouse'),
        ),
        migrations.AddField(
            model_name='pressure_sensor',
            name='location_for_warehouse',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.warehouse', verbose_name='Location For Warehouse'),
        ),
        migrations.AddField(
            model_name='supply_orifice',
            name='location_for_warehouse',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.warehouse', verbose_name='Location For Warehouse'),
        ),
        migrations.AddField(
            model_name='swabmastertsr',
            name='location_for_warehouse',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.warehouse', verbose_name='Location For Warehouse'),
        ),
        migrations.AddField(
            model_name='ttd_tube_seal_rack',
            name='location_for_warehouse',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.warehouse', verbose_name='Location For Warehouse'),
        ),
    ]
