# Generated by Django 3.2.16 on 2023-04-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0038_auto_20230424_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='location_for_warehouse',
        ),
    ]
