# Generated by Django 3.2.16 on 2023-04-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0040_auto_20230426_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdd_tube_seal_rack',
            name='asset_number',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='bdd_tube_seal_rack',
            name='dimension',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dimension'),
        ),
        migrations.AddField(
            model_name='bdd_tube_seal_rack',
            name='location_for_storage',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='bdd_tube_seal_rack',
            name='name_of_abbreviation',
            field=models.CharField(blank=True, max_length=128, verbose_name='Abbreviation'),
        ),
        migrations.AddField(
            model_name='bdd_tube_seal_rack',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bdd_tube_seal_rack',
            name='packaging',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='bdd_tube_seal_rack',
            name='part_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='bdd_tube_seal_rack',
            name='pm_status',
            field=models.CharField(blank=True, choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bdd_tube_seal_rack',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='bdd_tube_seal_rack',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='media/images/general_parts'),
        ),
        migrations.AddField(
            model_name='bdd_tube_seal_rack',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Weight'),
        ),
        migrations.AddField(
            model_name='calibration_orifice',
            name='asset_number',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='calibration_orifice',
            name='dimension',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dimension'),
        ),
        migrations.AddField(
            model_name='calibration_orifice',
            name='location_for_storage',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='calibration_orifice',
            name='name_of_abbreviation',
            field=models.CharField(blank=True, max_length=128, verbose_name='Abbreviation'),
        ),
        migrations.AddField(
            model_name='calibration_orifice',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calibration_orifice',
            name='packaging',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='calibration_orifice',
            name='part_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='calibration_orifice',
            name='pm_status',
            field=models.CharField(blank=True, choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='calibration_orifice',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='calibration_orifice',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='media/images/general_parts'),
        ),
        migrations.AddField(
            model_name='calibration_orifice',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Weight'),
        ),
        migrations.AddField(
            model_name='devicehose',
            name='asset_number',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='devicehose',
            name='dimension',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dimension'),
        ),
        migrations.AddField(
            model_name='devicehose',
            name='location_for_storage',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='devicehose',
            name='name_of_abbreviation',
            field=models.CharField(blank=True, max_length=128, verbose_name='Abbreviation'),
        ),
        migrations.AddField(
            model_name='devicehose',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicehose',
            name='packaging',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='devicehose',
            name='part_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='devicehose',
            name='pm_status',
            field=models.CharField(blank=True, choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='devicehose',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='devicehose',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='media/images/general_parts'),
        ),
        migrations.AddField(
            model_name='devicehose',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Weight'),
        ),
        migrations.AddField(
            model_name='pressure_sensor',
            name='asset_number',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='pressure_sensor',
            name='dimension',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dimension'),
        ),
        migrations.AddField(
            model_name='pressure_sensor',
            name='location_for_storage',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='pressure_sensor',
            name='name_of_abbreviation',
            field=models.CharField(blank=True, max_length=128, verbose_name='Abbreviation'),
        ),
        migrations.AddField(
            model_name='pressure_sensor',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pressure_sensor',
            name='packaging',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='pressure_sensor',
            name='part_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pressure_sensor',
            name='pm_status',
            field=models.CharField(blank=True, choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pressure_sensor',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='pressure_sensor',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='media/images/general_parts'),
        ),
        migrations.AddField(
            model_name='pressure_sensor',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Weight'),
        ),
        migrations.AddField(
            model_name='supply_orifice',
            name='asset_number',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='supply_orifice',
            name='dimension',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dimension'),
        ),
        migrations.AddField(
            model_name='supply_orifice',
            name='location_for_storage',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='supply_orifice',
            name='name_of_abbreviation',
            field=models.CharField(blank=True, max_length=128, verbose_name='Abbreviation'),
        ),
        migrations.AddField(
            model_name='supply_orifice',
            name='packaging',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='supply_orifice',
            name='part_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='supply_orifice',
            name='pm_status',
            field=models.CharField(blank=True, choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supply_orifice',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='supply_orifice',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='media/images/general_parts'),
        ),
        migrations.AddField(
            model_name='supply_orifice',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Weight'),
        ),
        migrations.AddField(
            model_name='swabmastertsr',
            name='asset_number',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='swabmastertsr',
            name='dimension',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dimension'),
        ),
        migrations.AddField(
            model_name='swabmastertsr',
            name='location_for_storage',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='swabmastertsr',
            name='name_of_abbreviation',
            field=models.CharField(blank=True, max_length=128, verbose_name='Abbreviation'),
        ),
        migrations.AddField(
            model_name='swabmastertsr',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swabmastertsr',
            name='packaging',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='swabmastertsr',
            name='part_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='swabmastertsr',
            name='pm_status',
            field=models.CharField(blank=True, choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='swabmastertsr',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='swabmastertsr',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='media/images/general_parts'),
        ),
        migrations.AddField(
            model_name='swabmastertsr',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Weight'),
        ),
        migrations.AddField(
            model_name='ttd_tube_seal_rack',
            name='asset_number',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ttd_tube_seal_rack',
            name='dimension',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dimension'),
        ),
        migrations.AddField(
            model_name='ttd_tube_seal_rack',
            name='location_for_storage',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ttd_tube_seal_rack',
            name='name_of_abbreviation',
            field=models.CharField(blank=True, max_length=128, verbose_name='Abbreviation'),
        ),
        migrations.AddField(
            model_name='ttd_tube_seal_rack',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ttd_tube_seal_rack',
            name='packaging',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ttd_tube_seal_rack',
            name='part_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ttd_tube_seal_rack',
            name='pm_status',
            field=models.CharField(blank=True, choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ttd_tube_seal_rack',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='ttd_tube_seal_rack',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='media/images/general_parts'),
        ),
        migrations.AddField(
            model_name='ttd_tube_seal_rack',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='supply_orifice',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
