# Generated by Django 3.2.16 on 2023-04-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0041_auto_20230426_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airhose',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='bdd_tube_seal_rack',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='calibration_orifice',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='devicehose',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='part',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='pressure_sensor',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='supply_orifice',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='swabmastertsr',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='ttd_tube_seal_rack',
            name='dimension',
        ),
        migrations.AddField(
            model_name='airhose',
            name='breadth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airhose',
            name='dimension_unit',
            field=models.CharField(blank=True, choices=[('METER', 'Meter'), ('CM', 'Cm'), ('MM', 'Mm'), ('DECIMETER', 'Decimeter'), ('INCH', 'Inch')], max_length=50, null=True, verbose_name='Unit for Dimensions'),
        ),
        migrations.AddField(
            model_name='airhose',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bdd_tube_seal_rack',
            name='breadth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bdd_tube_seal_rack',
            name='dimension_unit',
            field=models.CharField(blank=True, choices=[('METER', 'Meter'), ('CM', 'Cm'), ('MM', 'Mm'), ('DECIMETER', 'Decimeter'), ('INCH', 'Inch')], max_length=50, null=True, verbose_name='Unit for Dimensions'),
        ),
        migrations.AddField(
            model_name='bdd_tube_seal_rack',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bdd_tube_seal_rack',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calibration_orifice',
            name='breadth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calibration_orifice',
            name='dimension_unit',
            field=models.CharField(blank=True, choices=[('METER', 'Meter'), ('CM', 'Cm'), ('MM', 'Mm'), ('DECIMETER', 'Decimeter'), ('INCH', 'Inch')], max_length=50, null=True, verbose_name='Unit for Dimensions'),
        ),
        migrations.AddField(
            model_name='calibration_orifice',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calibration_orifice',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicehose',
            name='breadth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicehose',
            name='dimension_unit',
            field=models.CharField(blank=True, choices=[('METER', 'Meter'), ('CM', 'Cm'), ('MM', 'Mm'), ('DECIMETER', 'Decimeter'), ('INCH', 'Inch')], max_length=50, null=True, verbose_name='Unit for Dimensions'),
        ),
        migrations.AddField(
            model_name='devicehose',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='breadth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='dimension_unit',
            field=models.CharField(blank=True, choices=[('METER', 'Meter'), ('CM', 'Cm'), ('MM', 'Mm'), ('DECIMETER', 'Decimeter'), ('INCH', 'Inch')], max_length=50, null=True, verbose_name='Unit for Dimensions'),
        ),
        migrations.AddField(
            model_name='part',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pressure_sensor',
            name='breadth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pressure_sensor',
            name='dimension_unit',
            field=models.CharField(blank=True, choices=[('METER', 'Meter'), ('CM', 'Cm'), ('MM', 'Mm'), ('DECIMETER', 'Decimeter'), ('INCH', 'Inch')], max_length=50, null=True, verbose_name='Unit for Dimensions'),
        ),
        migrations.AddField(
            model_name='pressure_sensor',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pressure_sensor',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supply_orifice',
            name='breadth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supply_orifice',
            name='dimension_unit',
            field=models.CharField(blank=True, choices=[('METER', 'Meter'), ('CM', 'Cm'), ('MM', 'Mm'), ('DECIMETER', 'Decimeter'), ('INCH', 'Inch')], max_length=50, null=True, verbose_name='Unit for Dimensions'),
        ),
        migrations.AddField(
            model_name='supply_orifice',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supply_orifice',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swabmastertsr',
            name='breadth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swabmastertsr',
            name='dimension_unit',
            field=models.CharField(blank=True, choices=[('METER', 'Meter'), ('CM', 'Cm'), ('MM', 'Mm'), ('DECIMETER', 'Decimeter'), ('INCH', 'Inch')], max_length=50, null=True, verbose_name='Unit for Dimensions'),
        ),
        migrations.AddField(
            model_name='swabmastertsr',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swabmastertsr',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ttd_tube_seal_rack',
            name='breadth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ttd_tube_seal_rack',
            name='dimension_unit',
            field=models.CharField(blank=True, choices=[('METER', 'Meter'), ('CM', 'Cm'), ('MM', 'Mm'), ('DECIMETER', 'Decimeter'), ('INCH', 'Inch')], max_length=50, null=True, verbose_name='Unit for Dimensions'),
        ),
        migrations.AddField(
            model_name='ttd_tube_seal_rack',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ttd_tube_seal_rack',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airhose',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicehose',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
