# Generated by Django 3.2.16 on 2023-04-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0042_auto_20230427_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='airhose',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('KG', 'Kg'), ('LBS', 'Lbs')], max_length=50, null=True, verbose_name='Unit for Weight'),
        ),
        migrations.AddField(
            model_name='bdd_tube_seal_rack',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('KG', 'Kg'), ('LBS', 'Lbs')], max_length=50, null=True, verbose_name='Unit for Weight'),
        ),
        migrations.AddField(
            model_name='calibration_orifice',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('KG', 'Kg'), ('LBS', 'Lbs')], max_length=50, null=True, verbose_name='Unit for Weight'),
        ),
        migrations.AddField(
            model_name='devicehose',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('KG', 'Kg'), ('LBS', 'Lbs')], max_length=50, null=True, verbose_name='Unit for Weight'),
        ),
        migrations.AddField(
            model_name='part',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('KG', 'Kg'), ('LBS', 'Lbs')], max_length=50, null=True, verbose_name='Unit for Weight'),
        ),
        migrations.AddField(
            model_name='pressure_sensor',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('KG', 'Kg'), ('LBS', 'Lbs')], max_length=50, null=True, verbose_name='Unit for Weight'),
        ),
        migrations.AddField(
            model_name='supply_orifice',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('KG', 'Kg'), ('LBS', 'Lbs')], max_length=50, null=True, verbose_name='Unit for Weight'),
        ),
        migrations.AddField(
            model_name='swabmastertsr',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('KG', 'Kg'), ('LBS', 'Lbs')], max_length=50, null=True, verbose_name='Unit for Weight'),
        ),
        migrations.AddField(
            model_name='ttd_tube_seal_rack',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('KG', 'Kg'), ('LBS', 'Lbs')], max_length=50, null=True, verbose_name='Unit for Weight'),
        ),
    ]
