# Generated by Django 3.2.16 on 2023-04-27 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0011_warehouse_country'),
        ('part', '0043_auto_20230427_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='location_for_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tube.warehouse'),
        ),
        migrations.AlterField(
            model_name='airhose',
            name='dimension_unit',
            field=models.CharField(blank=True, choices=[('CM', 'Cm'), ('MM', 'Mm'), ('INCH', 'Inch')], max_length=50, null=True, verbose_name='Unit for Dimensions'),
        ),
        migrations.AlterField(
            model_name='bdd_tube_seal_rack',
            name='dimension_unit',
            field=models.CharField(blank=True, choices=[('CM', 'Cm'), ('MM', 'Mm'), ('INCH', 'Inch')], max_length=50, null=True, verbose_name='Unit for Dimensions'),
        ),
        migrations.AlterField(
            model_name='calibration_orifice',
            name='dimension_unit',
            field=models.CharField(blank=True, choices=[('CM', 'Cm'), ('MM', 'Mm'), ('INCH', 'Inch')], max_length=50, null=True, verbose_name='Unit for Dimensions'),
        ),
        migrations.AlterField(
            model_name='devicehose',
            name='dimension_unit',
            field=models.CharField(blank=True, choices=[('CM', 'Cm'), ('MM', 'Mm'), ('INCH', 'Inch')], max_length=50, null=True, verbose_name='Unit for Dimensions'),
        ),
        migrations.AlterField(
            model_name='part',
            name='dimension_unit',
            field=models.CharField(blank=True, choices=[('CM', 'Cm'), ('MM', 'Mm'), ('INCH', 'Inch')], max_length=50, null=True, verbose_name='Unit for Dimensions'),
        ),
        migrations.AlterField(
            model_name='pressure_sensor',
            name='dimension_unit',
            field=models.CharField(blank=True, choices=[('CM', 'Cm'), ('MM', 'Mm'), ('INCH', 'Inch')], max_length=50, null=True, verbose_name='Unit for Dimensions'),
        ),
        migrations.AlterField(
            model_name='supply_orifice',
            name='dimension_unit',
            field=models.CharField(blank=True, choices=[('CM', 'Cm'), ('MM', 'Mm'), ('INCH', 'Inch')], max_length=50, null=True, verbose_name='Unit for Dimensions'),
        ),
        migrations.AlterField(
            model_name='swabmastertsr',
            name='dimension_unit',
            field=models.CharField(blank=True, choices=[('CM', 'Cm'), ('MM', 'Mm'), ('INCH', 'Inch')], max_length=50, null=True, verbose_name='Unit for Dimensions'),
        ),
        migrations.AlterField(
            model_name='ttd_tube_seal_rack',
            name='dimension_unit',
            field=models.CharField(blank=True, choices=[('CM', 'Cm'), ('MM', 'Mm'), ('INCH', 'Inch')], max_length=50, null=True, verbose_name='Unit for Dimensions'),
        ),
    ]
