# Generated by Django 3.2.16 on 2023-07-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0045_auto_20230530_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='airhose',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bdd_tube_seal_rack',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='calibration_orifice',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='devicehose',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pressure_sensor',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='supply_orifice',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='swabmastertsr',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ttd_tube_seal_rack',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='airhose',
            name='serial_number',
            field=models.CharField(default=1111, max_length=999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bdd_tube_seal_rack',
            name='serial_number',
            field=models.CharField(default=111, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calibration_orifice',
            name='serial_number',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicehose',
            name='serial_number',
            field=models.CharField(default=1, max_length=999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='part',
            name='serial_number',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='pressure_sensor',
            name='serial_number',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supply_orifice',
            name='serial_number',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='swabmastertsr',
            name='serial_number',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ttd_tube_seal_rack',
            name='serial_number',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
