# Generated by Django 3.2.16 on 2023-09-08 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0016_alter_warehouse_warehouse_name'),
        ('part', '0047_auto_20230907_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airhose',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airhose', to='tube.warehouse'),
        ),
        migrations.AlterField(
            model_name='bdd_tube_seal_rack',
            name='location_for_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bdd_rack', to='tube.warehouse', verbose_name='Location For Warehouse'),
        ),
        migrations.AlterField(
            model_name='calibration_orifice',
            name='location_for_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibration_orifice', to='tube.warehouse', verbose_name='Location For Warehouse'),
        ),
        migrations.AlterField(
            model_name='devicehose',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devicehose', to='tube.warehouse'),
        ),
        migrations.AlterField(
            model_name='part',
            name='location_for_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part', to='tube.warehouse'),
        ),
        migrations.AlterField(
            model_name='pressure_sensor',
            name='location_for_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pressure_sensor', to='tube.warehouse', verbose_name='Location For Warehouse'),
        ),
        migrations.AlterField(
            model_name='supply_orifice',
            name='location_for_warehouse',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_orifice', to='tube.warehouse', verbose_name='Location For Warehouse'),
        ),
        migrations.AlterField(
            model_name='swabmastertsr',
            name='location_for_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swabmasterTSR', to='tube.warehouse', verbose_name='Location For Warehouse'),
        ),
        migrations.AlterField(
            model_name='ttd_tube_seal_rack',
            name='location_for_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ttd_rack', to='tube.warehouse', verbose_name='Location For Warehouse'),
        ),
    ]
