# Generated by Django 4.1.1 on 2022-10-14 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0003_remove_equipment_warehouse_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
