# Generated by Django 3.2.16 on 2023-02-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0005_remove_bdd_bdd_tube_seal_rack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalyst',
            name='shape',
            field=models.CharField(blank=True, choices=[('TQ', 'TQ'), ('TABLET', 'TABLET'), ('EXTRADIET', 'EXTRADIET'), ('CYLINDER', 'CYLINDER'), ('PENTERING_CYLINDER', 'PENTERING_CYLINDER'), ('SPHERE', 'SPHERE'), ('OTHER', 'OTHER')], default='TQ', max_length=20),
        ),
        migrations.AlterField(
            model_name='loading',
            name='tube_bottom_retainer',
            field=models.CharField(blank=True, choices=[('SPRING', 'SPRING'), ('WIREMESH', 'WIREMESH'), ('OTHER', 'OTHER')], default='SPRING', max_length=20, null=True),
        ),
    ]
