# Generated by Django 3.2.16 on 2023-03-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0006_auto_20230210_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
