# Generated by Django 3.2.16 on 2023-03-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0008_alter_warehouse_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
