# Generated by Django 3.2.16 on 2023-04-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0009_alter_warehouse_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
