# Generated by Django 3.2.16 on 2023-04-24 08:22

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0010_alter_warehouse_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
