# Generated by Django 3.2.16 on 2023-05-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0012_auto_20230428_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_contact',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
