# Generated by Django 3.2.16 on 2023-07-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0015_alter_warehouse_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
