# Generated by Django 3.2.16 on 2023-09-14 10:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('part', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=128, verbose_name='Project Status')),
            ],
        ),
        migrations.CreateModel(
            name='Scope_of_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Project Name')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('project_number', models.IntegerField(blank=True, default='1', verbose_name='Project Number')),
                ('equipment_prep', models.DateField(blank=True, default=datetime.date.today, verbose_name='Equipment Prep')),
                ('equipment_ready', models.DateField(blank=True, default=datetime.date.today, verbose_name='Equipment Ready')),
                ('equipment_ship_client', models.DateField(blank=True, default=datetime.date.today, verbose_name='Equipment Ship Client')),
                ('equipment_delivery_client', models.DateField(blank=True, default=datetime.date.today, verbose_name='Equipment Delivery Client')),
                ('equipment_info_remarks', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Equipment Info Remarks')),
                ('project_start', models.DateField(blank=True, default=datetime.date.today, verbose_name='Project Start')),
                ('project_end', models.DateField(blank=True, default=datetime.date.today, verbose_name='Project End')),
                ('equipment_return_tubemaster', models.DateField(blank=True, default=datetime.date.today, verbose_name='Equipment Return Client')),
                ('equipment_delivery_tubemaster', models.DateField(blank=True, default=datetime.date.today, verbose_name='Equipment Delivery Tubemaster')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('contract', models.CharField(blank=True, choices=[('DIRECT', 'DIRECT'), ('SUB', 'SUB')], default='', max_length=128, null=True, verbose_name='Contract')),
                ('if_sub_client_name', models.CharField(blank=True, max_length=128, verbose_name='If Sub Contract Then Client Name')),
                ('general_remarks', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='General Remarks')),
                ('airhose_part', models.ManyToManyField(blank=True, default='', related_name='projects', to='part.AirHose', verbose_name='Air Hose')),
                ('bdd', models.ManyToManyField(blank=True, default='', related_name='bdd', to='equipment.BDD', verbose_name='BDD')),
                ('calibration_orifice_part', models.ManyToManyField(blank=True, default='', related_name='projects', to='part.Calibration_orifice', verbose_name='Calibration Orifice')),
                ('calibration_stand', models.ManyToManyField(blank=True, related_name='calibration_stand', to='equipment.CALIBRATION_STAND', verbose_name='CALIBRATION STAND')),
                ('client', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Client Name')),
                ('device_part', models.ManyToManyField(blank=True, default='', related_name='projects', to='part.DeviceHose', verbose_name='Device Hose')),
                ('part', models.ManyToManyField(blank=True, default='', related_name='projects', to='part.Part')),
                ('project_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projectstatus', verbose_name='Project Status')),
                ('reactor', models.ManyToManyField(blank=True, to='client.Reactor', verbose_name='Reactor Name')),
                ('scope_of_work', models.ManyToManyField(blank=True, to='project.Scope_of_work', verbose_name='Scope Of Work')),
                ('swabmaster_equip', models.ManyToManyField(blank=True, related_name='Swabmaster', to='equipment.SwabMaster', verbose_name='Swab Master')),
                ('ttd', models.ManyToManyField(blank=True, default='', related_name='ttd', to='equipment.TTD', verbose_name='TTD')),
                ('unit', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='client.unit', verbose_name='Unit Name')),
            ],
        ),
    ]
