# Generated by Django 4.1.1 on 2022-09-20 04:45

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('OFFICIAL', 'OFFICIAL'), ('SHIPPING ', 'SHIPPING '), ('PLANTENTRANCE', 'PLANTENTRANCE')], default='OFFICIAL', max_length=20)),
                ('addressline1', models.CharField(default='', max_length=128)),
                ('addressline2', models.CharField(default='', max_length=128)),
                ('addressline3', models.CharField(default='', max_length=128)),
                ('city', models.CharField(default='', max_length=128)),
                ('state', models.CharField(default='', max_length=128)),
                ('country', models.CharField(default='', max_length=128)),
                ('zipcode', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_name', models.CharField(default='', max_length=128)),
                ('comman_name', models.CharField(default='', max_length=128)),
                ('alternate_name', models.CharField(default='', max_length=128)),
                ('key_contact', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
                ('parent_company', models.CharField(default='', max_length=128)),
                ('chemical', models.CharField(default='', max_length=128)),
                ('unitname', models.CharField(default='', max_length=128)),
                ('reactor_name', models.CharField(default='', max_length=128)),
                ('former_name', models.CharField(default='', max_length=128)),
                ('official_address', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='official_address', to='project.address', verbose_name='official_address')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_location', models.CharField(default='', max_length=128)),
                ('plant_contact', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Reactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reactor_name', models.CharField(default='', max_length=128)),
                ('tube_id_in', models.CharField(default='', max_length=128)),
                ('tube_id_mm', models.CharField(default='', max_length=128)),
                ('is_there_ferrule_insert_in_tube', models.BooleanField(choices=[(True, 'yes'), (False, 'No')], verbose_name='is_there_ferrule_insert_in_tube')),
                ('ferrule_length', models.CharField(default='', max_length=128)),
                ('ferrule_id', models.CharField(default='', max_length=128)),
                ('tube_material_of_tubes', models.CharField(default='', max_length=128)),
                ('tube_material_of_raws', models.CharField(default='', max_length=128)),
                ('tube_material_of_thermo', models.CharField(default='', max_length=128)),
                ('tube_material_of_supports', models.CharField(default='', max_length=128)),
                ('tube_material_of_plugs', models.CharField(default='', max_length=128)),
                ('tube_material_of_coolent_tubes', models.CharField(default='', max_length=128)),
                ('tube_spacing_in_or_pitch', models.CharField(default='', max_length=128)),
                ('tube_spacing_mm_or_pitch', models.CharField(default='', max_length=128)),
                ('tube_spacing_proof_document', models.FileField(null=True, upload_to='document/')),
                ('total_tube_length', models.CharField(default='', max_length=128)),
                ('top_tube_sheet_thickness', models.CharField(default='', max_length=128)),
                ('bottom_tube_sheet_thickness', models.CharField(default='', max_length=128)),
                ('tube_protude_out_of_top_tube_sheet', models.BooleanField(choices=[(True, 'yes'), (False, 'No')], verbose_name='tube_protude_out_of_top_tube_sheet')),
                ('tube_protude_out_of_bottom_tube_sheet', models.BooleanField(choices=[(True, 'yes'), (False, 'No')], verbose_name='tube_protude_out_of_bottom_tube_sheet')),
                ('top_dome_removable', models.BooleanField(choices=[(True, 'yes'), (False, 'No')], verbose_name='top_dome_removable')),
                ('top_inlet_accessible', models.BooleanField(choices=[(True, 'yes'), (False, 'No')], default='False', verbose_name='top_inlet_accessible')),
                ('top_inlet_impingment_plate', models.BooleanField(choices=[(True, 'yes'), (False, 'No')], verbose_name='top_inlet_impingment_plate')),
                ('any_projections_on_tube_sheet_describe', models.TextField(default='')),
                ('tube_sheet_material', models.CharField(default='', max_length=128)),
                ('dom_material', models.CharField(default='', max_length=128)),
                ('reactor_tube_sheet_drawings', models.FileField(null=True, upload_to='images/')),
                ('reactor_elevation_view_drawings', models.FileField(null=True, upload_to='images/')),
                ('other_drawings', models.FileField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='project.client', verbose_name='client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='plant',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='project.plant', verbose_name='plant'),
        ),
        migrations.AddField(
            model_name='client',
            name='plantentrance_address',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='plantentrance_address', to='project.address', verbose_name='plantentrance_address'),
        ),
        migrations.AddField(
            model_name='client',
            name='reactor',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='project.reactor', verbose_name='reactor'),
        ),
        migrations.AddField(
            model_name='client',
            name='shipping_address',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='shipping_address', to='project.address', verbose_name='shipping_address'),
        ),
    ]
