# Generated by Django 4.1.1 on 2022-11-15 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0090_remove_client_official_address_and_more'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='official_address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='client',
            name='plantentrance_address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='reactor',
        ),
        migrations.RemoveField(
            model_name='client',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='project',
            name='equipment_delivery_client',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='equipment_delivery_tubemaster',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='equipment_prep',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='equipment_ready',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='equipment_return_tubemaster',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='equipment_ship_client',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_end',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_number',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_start',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='reactor',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='client.reactor', verbose_name='Reactor Name'),
        ),
        migrations.AddField(
            model_name='project',
            name='unit',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='client.unit', verbose_name='Unit Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Client Name'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
        migrations.DeleteModel(
            name='Reactor',
        ),
    ]
