# Generated by Django 3.2.16 on 2023-09-18 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20230918_1549'),
        ('part', '0002_alter_supply_orifice_location_for_warehouse'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='airhose_part',
            field=models.ManyToManyField(blank=True, related_name='projects', to='part.AirHose', verbose_name='Air Hose'),
        ),
        migrations.AlterField(
            model_name='project',
            name='calibration_orifice_part',
            field=models.ManyToManyField(blank=True, related_name='projects', to='part.Calibration_orifice', verbose_name='Calibration Orifice'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract',
            field=models.CharField(blank=True, choices=[('DIRECT', 'DIRECT'), ('SUB', 'SUB')], max_length=128, null=True, verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='project',
            name='device_part',
            field=models.ManyToManyField(blank=True, related_name='projects', to='part.DeviceHose', verbose_name='Device Hose'),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_info_remarks',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Equipment Info Remarks'),
        ),
        migrations.AlterField(
            model_name='project',
            name='general_remarks',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='General Remarks'),
        ),
        migrations.AlterField(
            model_name='project',
            name='part',
            field=models.ManyToManyField(blank=True, related_name='projects', to='part.Part'),
        ),
        migrations.AlterField(
            model_name='project',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='client.unit', verbose_name='Unit Name'),
        ),
    ]
