# Generated by Django 4.1.1 on 2022-11-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_client_official_address_remove_client_plant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='chemical',
            field=models.CharField(default='', max_length=128, verbose_name='Chemical Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_delivery_client',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_prep',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_ready',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_ship_client',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_start',
            field=models.DateField(auto_now_add=True),
        ),
    ]
