# Generated by Django 4.1.1 on 2022-11-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_if_sub_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contract',
            field=models.CharField(blank=True, choices=[('DIRECT', 'DIRECT'), ('SUB', 'SUB')], default='DIRECT', max_length=128, verbose_name='Contract'),
        ),
    ]
