# Generated by Django 4.1.1 on 2022-11-28 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0092_remove_reactor_tube_material_of_rows_and_more'),
        ('project', '0008_project_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='chemical',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Chemical Name+', to='client.unit', verbose_name='Chemical Name'),
        ),
    ]
