# Generated by Django 4.1.1 on 2022-11-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_project_chemical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='chemical',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.IntegerField(blank=True, default='1'),
        ),
    ]
