# Generated by Django 4.1.1 on 2022-11-28 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_remove_project_chemical_alter_project_project_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='equipment_delivery_client',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Equipment Delivery Client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_delivery_tubemaster',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Equipment Delivery Tubemaster'),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_prep',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Equipment Prep'),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_ready',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Equipment Ready'),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_return_tubemaster',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Equipment Return Tubemaster'),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_ship_client',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Equipment Ship Client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_end',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Project End'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_start',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Project Start'),
        ),
    ]
