# Generated by Django 4.1.1 on 2022-12-08 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0110_alter_reactor_tube_id'),
        ('project', '0013_alter_project_contract_alter_project_scope_of_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='reactor',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='client.reactor', verbose_name='Reactor Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='unit',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='client.unit', verbose_name='Unit Name'),
        ),
    ]
