# Generated by Django 3.2.16 on 2023-02-10 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0041_auto_20230209_1622'),
        ('client', '0121_auto_20230210_1116'),
        ('project', '0024_alter_project_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bdd',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.bdd', verbose_name='BDD'),
        ),
        migrations.AlterField(
            model_name='project',
            name='calibration_stand',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.calibration_stand', verbose_name='CALIBRATION STAND'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract',
            field=models.CharField(blank=True, choices=[('DIRECT', 'DIRECT'), ('SUB', 'SUB')], default='', max_length=128, null=True, verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_info_remarks',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Equipment Info Remarks'),
        ),
        migrations.AlterField(
            model_name='project',
            name='general_remarks',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='General Remarks'),
        ),
        migrations.AlterField(
            model_name='project',
            name='reactor',
            field=models.ManyToManyField(blank=True, null=True, to='client.Reactor', verbose_name='Reactor Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='scope_of_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.scope_of_work', verbose_name='Scope Of Work'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ttd',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.ttd', verbose_name='TTD'),
        ),
        migrations.AlterField(
            model_name='project',
            name='unit',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='client.unit', verbose_name='Unit Name'),
        ),
    ]
