# Generated by Django 3.2.16 on 2023-02-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_alter_project_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='scope_of_work',
        ),
        migrations.AddField(
            model_name='project',
            name='scope_of_work',
            field=models.ManyToManyField(blank=True, null=True, to='project.Scope_of_work', verbose_name='Scope Of Work'),
        ),
    ]
