# Generated by Django 3.2.16 on 2023-03-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0045_alter_ttd_supply_orifice_set'),
        ('project', '0028_alter_project_scope_of_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='bdd',
        ),
        migrations.AddField(
            model_name='project',
            name='bdd',
            field=models.ManyToManyField(blank=True, default='', null=True, to='equipment.BDD', verbose_name='BDD'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='calibration_stand',
        ),
        migrations.AddField(
            model_name='project',
            name='calibration_stand',
            field=models.ManyToManyField(blank=True, null=True, to='equipment.CALIBRATION_STAND', verbose_name='CALIBRATION STAND'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='ttd',
        ),
        migrations.AddField(
            model_name='project',
            name='ttd',
            field=models.ManyToManyField(blank=True, default='', null=True, to='equipment.TTD', verbose_name='TTD'),
        ),
    ]
