# Generated by Django 3.2.16 on 2023-03-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0032_alter_bdd_tube_seal_rack_number_of_tubes'),
        ('project', '0029_auto_20230301_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='part',
        ),
        migrations.AddField(
            model_name='project',
            name='part',
            field=models.ManyToManyField(blank=True, default='', null=True, to='part.Part'),
        ),
    ]
