# Generated by Django 3.2.16 on 2023-03-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_auto_20230314_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Project Name'),
        ),
    ]
