# Generated by Django 3.2.16 on 2023-03-17 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0046_auto_20230314_0519'),
        ('project', '0033_project_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='bdd',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='bdd', to='equipment.BDD', verbose_name='BDD'),
        ),
        migrations.AlterField(
            model_name='project',
            name='calibration_stand',
            field=models.ManyToManyField(blank=True, null=True, related_name='calibration_stand', to='equipment.CALIBRATION_STAND', verbose_name='CALIBRATION STAND'),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipment_return_tubemaster',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Equipment Return Client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ttd',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='ttd', to='equipment.TTD', verbose_name='TTD'),
        ),
    ]
