# Generated by Django 3.2.16 on 2023-04-24 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0123_auto_20230302_0659'),
        ('project', '0035_alter_project_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Client Name'),
        ),
    ]
