# Generated by Django 3.2.16 on 2023-04-25 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0124_client_country'),
        ('project', '0038_auto_20230425_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='unit',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='client.unit', verbose_name='Unit Name'),
        ),
    ]
