# Generated by Django 3.2.16 on 2023-05-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0045_auto_20230530_1121'),
        ('project', '0040_auto_20230427_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='part',
            field=models.ManyToManyField(blank=True, default='', related_name='projects', to='part.Part'),
        ),
    ]
