# Generated by Django 3.2.16 on 2023-05-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0045_auto_20230530_1121'),
        ('project', '0041_alter_project_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='swabmaster_part',
            field=models.ManyToManyField(blank=True, default='', related_name='projects', to='part.SwabMasterTSR', verbose_name='Swab Master TSR'),
        ),
    ]
