# Generated by Django 3.2.16 on 2023-06-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0048_equipmentcollection'),
        ('project', '0043_auto_20230606_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='swabmaster_equip',
            field=models.ManyToManyField(blank=True, null=True, related_name='swabmaster', to='equipment.SwabMaster', verbose_name='Swab Master'),
        ),
    ]
