# Generated by Django 3.2.16 on 2023-06-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0048_equipmentcollection'),
        ('project', '0044_project_swabmaster_equip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='swabmaster_equip',
            field=models.ManyToManyField(blank=True, related_name='Swabmaster', to='equipment.SwabMaster', verbose_name='Swab Master'),
        ),
    ]
