# Generated by Django 3.2.16 on 2023-07-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0047_alter_project_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set(),
        ),
    ]
