# Generated by Django 3.2.16 on 2023-08-01 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0048_alter_project_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pressure_sensor_part',
        ),
        migrations.RemoveField(
            model_name='project',
            name='supply_orifice_part',
        ),
        migrations.RemoveField(
            model_name='project',
            name='swabmaster_part',
        ),
    ]
